/**
 * Summaries stage (arm-S input, D4 contract) and questions stage (golden
 * questions generated by the judge-model family, never the answer model).
 */

import { countTextTokens } from '@tzurot/common-types/utils/tokenCounter';
import type { CorpusResult, CorpusRow } from './render-pilot-corpus.js';
import {
  buildSummarizerUserMessage,
  buildQuestionUserMessage,
  buildTightenMessage,
  SUMMARIZER_SYSTEM_PROMPT,
  QUESTION_SYSTEM_PROMPT,
} from './render-pilot-prompts.js';
import {
  callChatCompletion,
  requireApiKey,
  runWithConcurrencySettled,
  clearStageUsage,
  type ChatMessage,
} from './render-pilot-llm.js';
import {
  parseSummaryResponse,
  parseQuestionsResponse,
  decideSummaryOutcome,
  hasFirstPerson,
  SUMMARY_SOFT_CAP_TOKENS,
  type SummaryRecord,
} from './render-pilot-metrics.js';
import {
  stagePath,
  readStageFile,
  writeStageFile,
  shouldRunStage,
  logUsage,
  partitionSettled,
  reportStageFailures,
  type RenderPilotOptions,
  type SlugContext,
  type StageCallFailure,
} from './render-pilot-shared.js';

export interface QuestionRecord {
  rowId: string;
  q: string;
  a: string;
  basis: 'assistant' | 'user';
}

interface SummarizerCallResult {
  text: string;
  tokens: number;
  /** True when the response failed strict-JSON parsing and the raw body was used as-is. */
  parseFailed: boolean;
}

async function callSummarizer(
  ctx: SlugContext,
  options: RenderPilotOptions,
  apiKey: string,
  messages: ChatMessage[]
): Promise<SummarizerCallResult> {
  const result = await callChatCompletion(
    // Cap must leave headroom for a reasoning model's thinking tokens, which are
    // emitted before any content: a live run at a tight cap came back
    // finish_reason "length" with no content at all. The thinking-first ordering
    // is inferred from that finish_reason, not separately probed — a live run at
    // a 3000 cap still came back finish_reason "length" with no content on the
    // largest rows, so the cap is 8000.
    {
      model: options.summaryModel,
      messages,
      temperature: 0.2,
      maxTokens: 8000,
      jsonMode: true,
      provider: options.glmProvider,
      thinking: options.summaryThinking,
    },
    apiKey
  );
  logUsage(ctx, 'summaries', options.summaryModel, result);
  const parsed = parseSummaryResponse(result.content);
  const text = parsed?.summary ?? result.content;
  if (text.trim().length === 0) {
    throw new Error('summarizer returned empty content');
  }
  return { text, tokens: countTextTokens(text), parseFailed: parsed === null };
}

async function summarizeOneRow(
  ctx: SlugContext,
  options: RenderPilotOptions,
  corpus: CorpusResult,
  row: CorpusRow,
  apiKey: string
): Promise<SummaryRecord & { rowId: string }> {
  const userMessage = buildSummarizerUserMessage({
    displayName: corpus.personality.displayName,
    subjectName: row.subjectName,
    userText: row.split.user,
    assistantText: row.split.assistant,
    referenced: row.split.referenced,
  });
  const first = await callSummarizer(ctx, options, apiKey, [
    { role: 'system', content: SUMMARIZER_SYSTEM_PROMPT },
    { role: 'user', content: userMessage },
  ]);

  const retry =
    first.tokens > SUMMARY_SOFT_CAP_TOKENS
      ? await callSummarizer(ctx, options, apiKey, [
          { role: 'system', content: SUMMARIZER_SYSTEM_PROMPT },
          { role: 'user', content: userMessage },
          { role: 'user', content: buildTightenMessage(first.text) },
        ])
      : null;
  const outcome = decideSummaryOutcome(first, retry);
  const chosenParseFailed =
    retry !== null && outcome.text === retry.text ? retry.parseFailed : first.parseFailed;
  return {
    rowId: row.id,
    summary: outcome.text,
    tokens: outcome.tokens,
    state: outcome.state,
    hasFirstPerson: hasFirstPerson(outcome.text),
    parseFailed: chosenParseFailed,
  };
}

/** On-disk shape of the summaries stage cache file. */
export interface SummariesStageFile {
  summaries: (SummaryRecord & { rowId: string })[];
  failures: StageCallFailure[];
}

/** D4: one summarizer call per row, with a length-triggered retry. */
export async function runSummariesStage(
  ctx: SlugContext,
  options: RenderPilotOptions,
  corpus: CorpusResult
): Promise<void> {
  const path = stagePath(ctx.outDir, ctx.slug, 'summaries');
  if (!shouldRunStage(options, 'summaries', path)) {
    return;
  }
  clearStageUsage(ctx.usageLogPath, 'summaries');
  const apiKey = ctx.apiKeys[options.glmProvider] ?? requireApiKey(options.glmProvider);
  const tasks = corpus.rows.map(row => () => summarizeOneRow(ctx, options, corpus, row, apiKey));
  const settled = await runWithConcurrencySettled(tasks, options.concurrency);
  const { values, failures } = partitionSettled(settled, index => ({
    rowId: corpus.rows[index].id,
  }));
  reportStageFailures('summaries', failures);
  const file: SummariesStageFile = { summaries: values, failures };
  writeStageFile(path, file);
}

async function generateQuestionsForRow(
  ctx: SlugContext,
  options: RenderPilotOptions,
  corpus: CorpusResult,
  row: CorpusRow,
  apiKey: string
): Promise<{ questions: QuestionRecord[]; dropped: number }> {
  const userMessage = buildQuestionUserMessage({
    displayName: corpus.personality.displayName,
    subjectName: row.subjectName,
    userText: row.split.user,
    assistantText: row.split.assistant,
    referenced: row.split.referenced,
    questionsPerRow: options.questionsPerRow,
  });
  const result = await callChatCompletion(
    {
      model: options.judgeModel,
      messages: [
        { role: 'system', content: QUESTION_SYSTEM_PROMPT },
        { role: 'user', content: userMessage },
      ],
      temperature: 0.3,
      // Cap must leave headroom for a reasoning model's thinking tokens, which are
      // emitted before any content: a live run at a tight cap came back
      // finish_reason "length" with no content at all. The thinking-first ordering
      // is inferred from that finish_reason, not separately probed.
      maxTokens: 2000,
      jsonMode: true,
      provider: 'openrouter',
    },
    apiKey
  );
  logUsage(ctx, 'questions', options.judgeModel, result);
  const { questions, dropped } = parseQuestionsResponse(result.content);
  return { questions: questions.map(q => ({ rowId: row.id, ...q })), dropped };
}

/** On-disk shape of the questions stage cache file. */
export interface QuestionsStageFile {
  questions: QuestionRecord[];
  /** Malformed question entries dropped by parseQuestionsResponse, summed across every row. */
  droppedMalformed: number;
  failures: StageCallFailure[];
}

/** One question-generator call per row, run by the judge-model family. */
export async function runQuestionsStage(
  ctx: SlugContext,
  options: RenderPilotOptions,
  corpus: CorpusResult
): Promise<void> {
  const path = stagePath(ctx.outDir, ctx.slug, 'questions');
  if (!shouldRunStage(options, 'questions', path)) {
    return;
  }
  clearStageUsage(ctx.usageLogPath, 'questions');
  const apiKey = ctx.apiKeys.openrouter ?? requireApiKey('openrouter');
  const tasks = corpus.rows.map(
    row => () => generateQuestionsForRow(ctx, options, corpus, row, apiKey)
  );
  const settled = await runWithConcurrencySettled(tasks, options.concurrency);
  const { values: perRow, failures } = partitionSettled(settled, index => ({
    rowId: corpus.rows[index].id,
  }));
  reportStageFailures('questions', failures);
  const file: QuestionsStageFile = {
    questions: perRow.flatMap(r => r.questions),
    droppedMalformed: perRow.reduce((sum, r) => sum + r.dropped, 0),
    failures,
  };
  writeStageFile(path, file);
}

/** Read the cached questions stage file, defaulting to empty when absent. */
export function loadQuestionsStageFile(outDir: string, slug: string): QuestionsStageFile {
  return (
    readStageFile<QuestionsStageFile>(stagePath(outDir, slug, 'questions')) ?? {
      questions: [],
      droppedMalformed: 0,
      failures: [],
    }
  );
}

/** Read the cached summaries stage file, defaulting to empty when absent. */
export function loadSummariesStageFile(outDir: string, slug: string): SummariesStageFile {
  return (
    readStageFile<SummariesStageFile>(stagePath(outDir, slug, 'summaries')) ?? {
      summaries: [],
      failures: [],
    }
  );
}

/** Read the cached summaries stage output, keyed by row id (empty map when absent). */
export function loadSummaryByRowId(outDir: string, slug: string): Map<string, SummaryRecord> {
  const { summaries } = loadSummariesStageFile(outDir, slug);
  return new Map(summaries.map(s => [s.rowId, s]));
}
