/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/common-types/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

import { z } from 'zod';
import { callGateway, type GatewayResult } from '../transport.js';
import { ROUTE_MANIFEST } from '../../routes/manifest.js';

function buildQueryString(entries: Array<[string, string | undefined]>): string {
  const defined = entries.filter((e): e is [string, string] => e[1] !== undefined);
  if (defined.length === 0) return '';
  const qs = new URLSearchParams();
  for (const [k, v] of defined) qs.set(k, v);
  return '?' + qs.toString();
}

export interface ServiceClientOptions {
  /** Full gateway base URL, e.g. https://api-gateway.example.com. */
  baseUrl: string;
  /** Shared service secret (sent as X-Service-Auth). */
  serviceSecret: string;
}

export class ServiceClient {
  private readonly baseUrl: string;
  private readonly serviceSecret: string;

  constructor(options: ServiceClientOptions) {
    this.baseUrl = options.baseUrl;
    this.serviceSecret = options.serviceSecret;
  }

  async aiGenerate(input: z.infer<typeof ROUTE_MANIFEST.aiGenerate.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.aiGenerate.output>>> {
    const fullPath = '/api/internal/ai/generate';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      body: input,
      outputSchema: ROUTE_MANIFEST.aiGenerate.output,
    });
  }

  async aiTranscribe(input: z.infer<typeof ROUTE_MANIFEST.aiTranscribe.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.aiTranscribe.output>>> {
    const fullPath = '/api/internal/ai/transcribe';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      body: input,
      outputSchema: ROUTE_MANIFEST.aiTranscribe.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async aiJobStatus(jobId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.aiJobStatus.output>>> {
    const fullPath = `/api/internal/ai/job/${encodeURIComponent(jobId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      outputSchema: ROUTE_MANIFEST.aiJobStatus.output,
    });
  }

  async aiConfirmDelivery(jobId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.aiConfirmDelivery.output>>> {
    const fullPath = `/api/internal/ai/job/${encodeURIComponent(jobId)}/confirm-delivery`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      outputSchema: ROUTE_MANIFEST.aiConfirmDelivery.output,
    });
  }

  async setDmSession(input: z.infer<typeof ROUTE_MANIFEST.setDmSession.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setDmSession.output>>> {
    const fullPath = '/api/internal/channel/dm-session/set';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      body: input,
      outputSchema: ROUTE_MANIFEST.setDmSession.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async lookupPersonalityFromMessage(options: { discordMessageId: string }): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.lookupPersonalityFromMessage.output>>> {
    const fullPath = '/api/internal/conversation/message-personality' + buildQueryString([['discordMessageId', options.discordMessageId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      outputSchema: ROUTE_MANIFEST.lookupPersonalityFromMessage.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async recentUsers(options: { sinceDays?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.recentUsers.output>>> {
    const fullPath = '/api/internal/users/recent' + buildQueryString([['sinceDays', options.sinceDays]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      outputSchema: ROUTE_MANIFEST.recentUsers.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getDenylistCache(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDenylistCache.output>>> {
    const fullPath = '/api/internal/denylist/cache';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      outputSchema: ROUTE_MANIFEST.getDenylistCache.output,
    });
  }

  async updateDiagnosticResponseIds(requestId: string, input: z.infer<typeof ROUTE_MANIFEST.updateDiagnosticResponseIds.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateDiagnosticResponseIds.output>>> {
    const fullPath = `/api/internal/diagnostic/${encodeURIComponent(requestId)}/response-ids`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      body: input,
      outputSchema: ROUTE_MANIFEST.updateDiagnosticResponseIds.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getChannelSettings(channelId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getChannelSettings.output>>> {
    const fullPath = `/api/internal/channel/${encodeURIComponent(channelId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      outputSchema: ROUTE_MANIFEST.getChannelSettings.output,
    });
  }
}
