/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/common-types/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

import { z } from 'zod';
import { callGateway, type GatewayResult } from '../transport.js';
import { ROUTE_MANIFEST } from '../../routes/manifest.js';
import { type ActorDiscordId, type SubjectDiscordId } from '../../routes/types.js';
import type { GatewayUser } from '../../types/gateway-context.js';

function buildQueryString(entries: Array<[string, string | undefined]>): string {
  const defined = entries.filter((e): e is [string, string] => e[1] !== undefined);
  if (defined.length === 0) return '';
  const qs = new URLSearchParams();
  for (const [k, v] of defined) qs.set(k, v);
  return '?' + qs.toString();
}

export interface UserClientOptions {
  /** Full gateway base URL, e.g. https://api-gateway.example.com. */
  baseUrl: string;
  /** Shared service secret (sent as X-Service-Auth). */
  serviceSecret: string;
  /** Discord ID of the actor making the call (the bot owner / the user). */
  actor: ActorDiscordId;
  /** Full Discord user context for user-context headers. */
  user: GatewayUser;
}

export class UserClient {
  private readonly baseUrl: string;
  private readonly serviceSecret: string;
  private readonly actor: ActorDiscordId;
  private readonly user: GatewayUser;

  constructor(options: UserClientOptions) {
    this.baseUrl = options.baseUrl;
    this.serviceSecret = options.serviceSecret;
    this.actor = options.actor;
    this.user = options.user;
  }

  async getTimezone(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getTimezone.output>>> {
    const fullPath = '/api/user/timezone';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getTimezone.output,
    });
  }

  async setTimezone(input: z.infer<typeof ROUTE_MANIFEST.setTimezone.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setTimezone.output>>> {
    const fullPath = '/api/user/timezone';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setTimezone.output,
    });
  }

  async listUserLlmConfigs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listUserLlmConfigs.output>>> {
    const fullPath = '/api/user/llm-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listUserLlmConfigs.output,
    });
  }

  async getUserLlmConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserLlmConfig.output>>> {
    const fullPath = `/api/user/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getUserLlmConfig.output,
    });
  }

  async createUserLlmConfig(input: z.infer<typeof ROUTE_MANIFEST.createUserLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createUserLlmConfig.output>>> {
    const fullPath = '/api/user/llm-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createUserLlmConfig.output,
    });
  }

  async updateUserLlmConfig(id: string, input: z.infer<typeof ROUTE_MANIFEST.updateUserLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateUserLlmConfig.output>>> {
    const fullPath = `/api/user/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateUserLlmConfig.output,
    });
  }

  async deleteUserLlmConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteUserLlmConfig.output>>> {
    const fullPath = `/api/user/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deleteUserLlmConfig.output,
    });
  }

  async resolveUserLlmConfig(input: z.infer<typeof ROUTE_MANIFEST.resolveUserLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolveUserLlmConfig.output>>> {
    const fullPath = '/api/user/llm-config/resolve';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.resolveUserLlmConfig.output,
    });
  }

  async listUserTtsConfigs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listUserTtsConfigs.output>>> {
    const fullPath = '/api/user/tts-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listUserTtsConfigs.output,
    });
  }

  async getUserTtsConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserTtsConfig.output>>> {
    const fullPath = `/api/user/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getUserTtsConfig.output,
    });
  }

  async createUserTtsConfig(input: z.infer<typeof ROUTE_MANIFEST.createUserTtsConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createUserTtsConfig.output>>> {
    const fullPath = '/api/user/tts-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createUserTtsConfig.output,
    });
  }

  async updateUserTtsConfig(id: string, input: z.infer<typeof ROUTE_MANIFEST.updateUserTtsConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateUserTtsConfig.output>>> {
    const fullPath = `/api/user/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateUserTtsConfig.output,
    });
  }

  async deleteUserTtsConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteUserTtsConfig.output>>> {
    const fullPath = `/api/user/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deleteUserTtsConfig.output,
    });
  }

  async listTtsOverrides(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listTtsOverrides.output>>> {
    const fullPath = '/api/user/tts-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listTtsOverrides.output,
    });
  }

  async setTtsOverride(input: z.infer<typeof ROUTE_MANIFEST.setTtsOverride.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setTtsOverride.output>>> {
    const fullPath = '/api/user/tts-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setTtsOverride.output,
    });
  }

  async deleteTtsOverride(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteTtsOverride.output>>> {
    const fullPath = `/api/user/tts-override/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deleteTtsOverride.output,
    });
  }

  async getTtsDefaultConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getTtsDefaultConfig.output>>> {
    const fullPath = '/api/user/tts-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getTtsDefaultConfig.output,
    });
  }

  async setTtsDefaultConfig(input: z.infer<typeof ROUTE_MANIFEST.setTtsDefaultConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setTtsDefaultConfig.output>>> {
    const fullPath = '/api/user/tts-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setTtsDefaultConfig.output,
    });
  }

  async clearTtsDefaultConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearTtsDefaultConfig.output>>> {
    const fullPath = '/api/user/tts-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearTtsDefaultConfig.output,
    });
  }

  async getSttDefaultProvider(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getSttDefaultProvider.output>>> {
    const fullPath = '/api/user/stt-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getSttDefaultProvider.output,
    });
  }

  async setSttDefaultProvider(input: z.infer<typeof ROUTE_MANIFEST.setSttDefaultProvider.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setSttDefaultProvider.output>>> {
    const fullPath = '/api/user/stt-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setSttDefaultProvider.output,
    });
  }

  async clearSttDefaultProvider(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearSttDefaultProvider.output>>> {
    const fullPath = '/api/user/stt-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearSttDefaultProvider.output,
    });
  }

  async listModelOverrides(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listModelOverrides.output>>> {
    const fullPath = '/api/user/model-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listModelOverrides.output,
    });
  }

  async setModelOverride(input: z.infer<typeof ROUTE_MANIFEST.setModelOverride.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setModelOverride.output>>> {
    const fullPath = '/api/user/model-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setModelOverride.output,
    });
  }

  async deleteModelOverride(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteModelOverride.output>>> {
    const fullPath = `/api/user/model-override/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deleteModelOverride.output,
    });
  }

  async getDefaultModelConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDefaultModelConfig.output>>> {
    const fullPath = '/api/user/model-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getDefaultModelConfig.output,
    });
  }

  async setDefaultModelConfig(input: z.infer<typeof ROUTE_MANIFEST.setDefaultModelConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setDefaultModelConfig.output>>> {
    const fullPath = '/api/user/model-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setDefaultModelConfig.output,
    });
  }

  async clearDefaultModelConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearDefaultModelConfig.output>>> {
    const fullPath = '/api/user/model-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearDefaultModelConfig.output,
    });
  }

  async listPersonalities(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonalities.output>>> {
    const fullPath = '/api/user/personality';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listPersonalities.output,
    });
  }

  async getPersonality(slug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getPersonality.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getPersonality.output,
    });
  }

  async createPersonality(input: z.infer<typeof ROUTE_MANIFEST.createPersonality.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createPersonality.output>>> {
    const fullPath = '/api/user/personality';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createPersonality.output,
    });
  }

  async updatePersonality(slug: string, input: z.infer<typeof ROUTE_MANIFEST.updatePersonality.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersonality.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersonality.output,
    });
  }

  async setPersonalityVisibility(slug: string, input: z.infer<typeof ROUTE_MANIFEST.setPersonalityVisibility.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setPersonalityVisibility.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}/visibility`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setPersonalityVisibility.output,
    });
  }

  async deletePersonality(slug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deletePersonality.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deletePersonality.output,
    });
  }

  async listPersonas(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonas.output>>> {
    const fullPath = '/api/user/persona';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listPersonas.output,
    });
  }

  async getPersona(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getPersona.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getPersona.output,
    });
  }

  async createPersona(input: z.infer<typeof ROUTE_MANIFEST.createPersona.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createPersona.output>>> {
    const fullPath = '/api/user/persona';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createPersona.output,
    });
  }

  async updatePersona(id: string, input: z.infer<typeof ROUTE_MANIFEST.updatePersona.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersona.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersona.output,
    });
  }

  async deletePersona(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deletePersona.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deletePersona.output,
    });
  }

  async setPersonaDefault(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setPersonaDefault.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}/default`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.setPersonaDefault.output,
    });
  }

  async listPersonaOverrides(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonaOverrides.output>>> {
    const fullPath = '/api/user/persona/override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listPersonaOverrides.output,
    });
  }

  async getPersonaOverride(personalitySlug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/${encodeURIComponent(personalitySlug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getPersonaOverride.output,
    });
  }

  async setPersonaOverride(personalitySlug: string, input: z.infer<typeof ROUTE_MANIFEST.setPersonaOverride.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/${encodeURIComponent(personalitySlug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setPersonaOverride.output,
    });
  }

  async clearPersonaOverride(personalitySlug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/${encodeURIComponent(personalitySlug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearPersonaOverride.output,
    });
  }

  async activateChannel(input: z.infer<typeof ROUTE_MANIFEST.activateChannel.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.activateChannel.output>>> {
    const fullPath = '/api/user/channel/activate';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.activateChannel.output,
    });
  }

  async deactivateChannel(input: z.infer<typeof ROUTE_MANIFEST.deactivateChannel.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deactivateChannel.output>>> {
    const fullPath = '/api/user/channel/deactivate';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.deactivateChannel.output,
    });
  }

  async listUserChannels(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listUserChannels.output>>> {
    const fullPath = '/api/user/channel/list';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listUserChannels.output,
    });
  }

  async getUserChannel(channelId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserChannel.output>>> {
    const fullPath = `/api/user/channel/${encodeURIComponent(channelId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getUserChannel.output,
    });
  }

  async updateChannelGuild(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateChannelGuild.output>>> {
    const fullPath = '/api/user/channel/update-guild';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.updateChannelGuild.output,
    });
  }

  async getChannelConfigOverrides(channelId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getChannelConfigOverrides.output>>> {
    const fullPath = `/api/user/channel/${encodeURIComponent(channelId)}/config-overrides`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getChannelConfigOverrides.output,
    });
  }

  async getUserUsage(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserUsage.output>>> {
    const fullPath = '/api/user/usage';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getUserUsage.output,
    });
  }

  async clearHistory(input: z.infer<typeof ROUTE_MANIFEST.clearHistory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearHistory.output>>> {
    const fullPath = '/api/user/history/clear';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.clearHistory.output,
    });
  }

  async undoHistory(input: z.infer<typeof ROUTE_MANIFEST.undoHistory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.undoHistory.output>>> {
    const fullPath = '/api/user/history/undo';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.undoHistory.output,
    });
  }

  async getHistoryStats(options: { personalitySlug?: string; channelId?: string; personaId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getHistoryStats.output>>> {
    const fullPath = '/api/user/history/stats' + buildQueryString([['personalitySlug', options.personalitySlug], ['channelId', options.channelId], ['personaId', options.personaId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getHistoryStats.output,
    });
  }

  async hardDeleteHistory(input: z.infer<typeof ROUTE_MANIFEST.hardDeleteHistory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.hardDeleteHistory.output>>> {
    const fullPath = '/api/user/history/hard-delete';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.hardDeleteHistory.output,
    });
  }

  async getNsfwStatus(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getNsfwStatus.output>>> {
    const fullPath = '/api/user/nsfw';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getNsfwStatus.output,
    });
  }

  async verifyNsfw(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.verifyNsfw.output>>> {
    const fullPath = '/api/user/nsfw/verify';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.verifyNsfw.output,
    });
  }

  async listWalletKeys(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listWalletKeys.output>>> {
    const fullPath = '/api/user/wallet/list';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listWalletKeys.output,
    });
  }

  async setWalletKey(input: z.infer<typeof ROUTE_MANIFEST.setWalletKey.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setWalletKey.output>>> {
    const fullPath = '/api/user/wallet';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setWalletKey.output,
    });
  }

  async removeWalletKey(provider: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.removeWalletKey.output>>> {
    const fullPath = `/api/user/wallet/${encodeURIComponent(provider)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.removeWalletKey.output,
    });
  }

  async testWalletKey(input: z.infer<typeof ROUTE_MANIFEST.testWalletKey.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.testWalletKey.output>>> {
    const fullPath = '/api/user/wallet/test';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.testWalletKey.output,
    });
  }

  async getVoiceResolution(options: { personalityId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getVoiceResolution.output>>> {
    const fullPath = '/api/user/voice-resolution' + buildQueryString([['personalityId', options.personalityId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getVoiceResolution.output,
    });
  }

  async listVoices(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listVoices.output>>> {
    const fullPath = '/api/user/voices';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listVoices.output,
    });
  }

  async listVoiceModels(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listVoiceModels.output>>> {
    const fullPath = '/api/user/voices/models';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.listVoiceModels.output,
    });
  }

  async clearVoices(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearVoices.output>>> {
    const fullPath = '/api/user/voices/clear';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearVoices.output,
    });
  }

  async deleteVoice(provider: string, voiceId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteVoice.output>>> {
    const fullPath = `/api/user/voices/${encodeURIComponent(provider)}/${encodeURIComponent(voiceId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.deleteVoice.output,
    });
  }

  async getIncognitoStatus(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getIncognitoStatus.output>>> {
    const fullPath = '/api/user/memory/incognito';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getIncognitoStatus.output,
    });
  }

  async enableIncognito(input: z.infer<typeof ROUTE_MANIFEST.enableIncognito.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.enableIncognito.output>>> {
    const fullPath = '/api/user/memory/incognito';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.enableIncognito.output,
    });
  }

  async disableIncognito(input: z.infer<typeof ROUTE_MANIFEST.disableIncognito.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.disableIncognito.output>>> {
    const fullPath = '/api/user/memory/incognito';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.disableIncognito.output,
    });
  }

  async incognitoForget(input: z.infer<typeof ROUTE_MANIFEST.incognitoForget.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.incognitoForget.output>>> {
    const fullPath = '/api/user/memory/incognito/forget';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.incognitoForget.output,
    });
  }

  async resolveUserDefaults(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolveUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/resolve-defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.resolveUserDefaults.output,
    });
  }

  async getUserDefaults(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getUserDefaults.output,
    });
  }

  async updateUserDefaults(input: z.infer<typeof ROUTE_MANIFEST.updateUserDefaults.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateUserDefaults.output,
    });
  }

  async clearUserDefaults(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearUserDefaults.output,
    });
  }

  async resolveCascade(personalityId: string, options: { channelId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolveCascade.output>>> {
    const fullPath = `/api/user/config-overrides/resolve/${encodeURIComponent(personalityId)}` + buildQueryString([['channelId', options.channelId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.resolveCascade.output,
    });
  }

  async updatePersonalityOverrides(personalityId: string, input: z.infer<typeof ROUTE_MANIFEST.updatePersonalityOverrides.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersonalityOverrides.output>>> {
    const fullPath = `/api/user/config-overrides/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersonalityOverrides.output,
    });
  }

  async clearPersonalityOverrides(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearPersonalityOverrides.output>>> {
    const fullPath = `/api/user/config-overrides/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.clearPersonalityOverrides.output,
    });
  }

  async resolvePersonalityCascade(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolvePersonalityCascade.output>>> {
    const fullPath = `/api/user/config-overrides/resolve-personality/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.resolvePersonalityCascade.output,
    });
  }

  async updatePersonalityConfigDefaults(personalityId: string, input: z.infer<typeof ROUTE_MANIFEST.updatePersonalityConfigDefaults.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersonalityConfigDefaults.output>>> {
    const fullPath = `/api/user/config-overrides/personality/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersonalityConfigDefaults.output,
    });
  }

  async getRecentDiagnostics(options: { subject?: SubjectDiscordId; personalityId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getRecentDiagnostics.output>>> {
    const fullPath = '/api/user/diagnostic/recent' + buildQueryString([['userId', options.subject], ['personalityId', options.personalityId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getRecentDiagnostics.output,
    });
  }

  async getDiagnosticByMessage(messageId: string, options: { subject?: SubjectDiscordId } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDiagnosticByMessage.output>>> {
    const fullPath = `/api/user/diagnostic/by-message/${encodeURIComponent(messageId)}` + buildQueryString([['userId', options.subject]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getDiagnosticByMessage.output,
    });
  }

  async getDiagnosticByResponse(messageId: string, options: { subject?: SubjectDiscordId } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDiagnosticByResponse.output>>> {
    const fullPath = `/api/user/diagnostic/by-response/${encodeURIComponent(messageId)}` + buildQueryString([['userId', options.subject]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getDiagnosticByResponse.output,
    });
  }

  async getDiagnosticByRequestId(requestId: string, options: { subject?: SubjectDiscordId } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDiagnosticByRequestId.output>>> {
    const fullPath = `/api/user/diagnostic/${encodeURIComponent(requestId)}` + buildQueryString([['userId', options.subject]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
      },
      outputSchema: ROUTE_MANIFEST.getDiagnosticByRequestId.output,
    });
  }
}
