/**
 * Character Overrides Dashboard
 *
 * Interactive dashboard for managing per-user per-character config overrides.
 * Shows effective values from the full cascade with source indicators.
 * Any user can set their own overrides for any personality.
 *
 * Settings: the non-admin cascade settings on the shared concern pages
 * (Memory · Context & Display · Voice, from `buildCascadePages`).
 */

import { type EnvConfig } from '@tzurot/common-types/config/config';
import { DISCORD_COLORS } from '@tzurot/common-types/constants/discord';
import { characterSettingsOptions } from '@tzurot/common-types/generated/commandOptions';
import { createLogger } from '@tzurot/common-types/utils/logger';
import type { DeferredCommandContext } from '../../utils/commandContext/types.js';
import {
  type SettingsDashboardConfig,
  type SettingUpdateHandler,
  type SettingsResetHandler,
  createSettingsCommandHandlers,
  VOICE_CASCADE_SETTINGS,
  buildCascadePages,
} from '../../utils/dashboard/settings/index.js';
import {
  createSettingsResetHandler,
  createSettingsUpdateHandler,
  type SettingUpdateConfig,
} from '../../utils/dashboard/settings/settingsUpdateFactory.js';
import { openCharacterCascadeDashboard } from './characterDashboardShared.js';

const logger = createLogger('character-overrides');

/**
 * Entity type for custom IDs
 * Uses hyphen separator to avoid conflicts with :: delimiter
 * CommandHandler uses alias mapping to route 'character-overrides' → 'character'
 */
const ENTITY_TYPE = 'character-overrides';

/** The shared D14 page grouping; a non-admin tier's Voice page is the cascade subset. */
const CASCADE_PAGES = buildCascadePages(VOICE_CASCADE_SETTINGS);

/**
 * Dashboard configuration for character overrides
 */
export const CHARACTER_OVERRIDES_CONFIG: SettingsDashboardConfig = {
  level: 'personality',
  entityType: ENTITY_TYPE,
  titlePrefix: 'Character Override',
  color: DISCORD_COLORS.BLURPLE,
  settings: CASCADE_PAGES.settings,
  pages: CASCADE_PAGES.pages,
  resetAll: true,
  scopeNote: name =>
    `👤 Applies only to your conversations with **${name}**. Nothing overrides these.`,
};

/**
 * Handle /character overrides command - shows interactive dashboard
 */
export async function handleOverrides(
  context: DeferredCommandContext,
  _config: EnvConfig
): Promise<void> {
  // Reuse characterSettingsOptions — same option shape (character: string)
  const options = characterSettingsOptions(context.interaction);

  await openCharacterCascadeDashboard(context, options.character(), {
    dashboardConfig: CHARACTER_OVERRIDES_CONFIG,
    sourceTier: 'user-personality',
    // Full user-personality cascade — any user's own override tier.
    resolveCascade: (uc, id) => uc.resolveCascade(id),
    noun: 'overrides',
    logger,
  });
}

/** Config for the character overrides update handler (full user-personality cascade) */
const CHARACTER_OVERRIDES_UPDATE_CONFIG: SettingUpdateConfig = {
  patchFn: (uc, id, body) => uc.updatePersonalityOverrides(id, body),
  resolveFn: (uc, id) => uc.resolveCascade(id),
  sourceTier: 'user-personality',
  logContext: '[Character Overrides]',
};

function createUpdateHandler(personalityId: string): SettingUpdateHandler {
  return createSettingsUpdateHandler(personalityId, CHARACTER_OVERRIDES_UPDATE_CONFIG);
}

function createResetHandler(personalityId: string): SettingsResetHandler {
  return createSettingsResetHandler(personalityId, CHARACTER_OVERRIDES_UPDATE_CONFIG);
}

// Interaction routers — generated by the shared factory so the 19-line
// guard/parse/forward pattern lives in exactly one place. See
// services/bot-client/src/utils/dashboard/settings/createSettingsCommandHandlers.ts
const characterOverridesHandlers = createSettingsCommandHandlers({
  entityType: ENTITY_TYPE,
  settingsConfig: CHARACTER_OVERRIDES_CONFIG,
  createUpdateHandler,
  createResetHandler,
});

export const handleCharacterOverridesSelectMenu = characterOverridesHandlers.handleSelectMenu;
export const handleCharacterOverridesButton = characterOverridesHandlers.handleButton;
export const handleCharacterOverridesModal = characterOverridesHandlers.handleModal;
export const isCharacterOverridesInteraction = characterOverridesHandlers.isInteraction;
