/**
 * Command Manifest Generator + Drift Guard
 *
 * Command modules in `services/bot-client/src/commands/*` cannot be imported
 * from a standalone/tooling context: some throw at module load (e.g. admin's
 * getConfig() requires REDIS_URL) and others open a Redis connection on import
 * (the batch import hangs). The ONLY clean way to load every command is through
 * CommandHandler with `redis.js` mocked, inside this vitest context.
 *
 * This test loads all commands and serializes a structural manifest to
 * `services/bot-client/command-manifest.json`, which the `pnpm ops commands:audit`
 * tooling consumer reads. On `-u` it (re)writes the manifest; without `-u` it
 * acts as a drift guard — failing if the committed manifest no longer matches
 * the live command surface.
 *
 * Refresh the manifest after any command-surface change:
 *   pnpm --filter @tzurot/bot-client test -- -u src/handlers/commandManifest.test.ts
 */

import { describe, it, expect, vi, beforeAll } from 'vitest';
import { SELECTOR_DESCRIPTION } from '@tzurot/common-types/constants/uxVocabulary';
import { CommandHandler } from './CommandHandler.js';
import { CATEGORY_CONFIG } from '../commands/help/index.js';
import type { Command } from '../types.js';

// Mock redis since several commands (e.g. character/chat.ts) import it at module
// load. Mirrors the mock used by CommandHandler.component.test.ts — without it,
// loading commands either throws or hangs on a real Redis connection. If a
// command starts using a redisService method not listed below (lrange, incr,
// etc.), loadCommands() throws here — add the missing method to this mock.
vi.mock('../redis.js', () => ({
  redisService: {
    get: vi.fn(),
    set: vi.fn(),
    del: vi.fn(),
    exists: vi.fn(),
    expire: vi.fn(),
    setWithExpiry: vi.fn(),
  },
}));

interface ManifestEntry {
  name: string;
  category: string | undefined;
  description: string;
  handlers: {
    execute: boolean;
    autocomplete: boolean;
    selectMenu: boolean;
    button: boolean;
    modal: boolean;
  };
  componentPrefixes: string[];
  data: ReturnType<Command['data']['toJSON']>;
}

function buildEntry(cmd: Command): ManifestEntry {
  return {
    name: cmd.data.name,
    category: cmd.category,
    description: cmd.data.description,
    handlers: {
      execute: !!cmd.execute,
      autocomplete: !!cmd.autocomplete,
      selectMenu: !!cmd.handleSelectMenu,
      button: !!cmd.handleButton,
      modal: !!cmd.handleModal,
    },
    componentPrefixes: cmd.componentPrefixes ?? [],
    data: cmd.data.toJSON(),
  };
}

describe('command manifest', () => {
  let handler: CommandHandler;

  beforeAll(async () => {
    handler = new CommandHandler();
    await handler.loadCommands();
  });

  it('generates the command manifest and guards against drift', async () => {
    const commands = [...handler.getCommands().values()]
      .map(buildEntry)
      .sort((a, b) => a.name.localeCompare(b.name));

    // Context-menu commands deploy through the same file scan as slash
    // commands, so they belong in the drift guard too — a deployed entry
    // absent here would be invisible to review.
    const contextMenuCommands = [...handler.getContextMenuCommands().values()]
      .map(cmd => ({
        name: cmd.data.name,
        category: cmd.category,
        data: cmd.data.toJSON(),
      }))
      .sort((a, b) => a.name.localeCompare(b.name));

    const manifest = {
      generatedNote:
        'AUTO-GENERATED by commandManifest.test.ts — do not edit by hand; run `pnpm --filter @tzurot/bot-client test -- -u` to refresh',
      helpCategories: Object.keys(CATEGORY_CONFIG),
      commands,
      contextMenuCommands,
    };

    // toMatchFileSnapshot resolves relative to the test file's directory
    // (src/handlers), so `../../command-manifest.json` lands at the
    // bot-client package root: services/bot-client/command-manifest.json.
    await expect(JSON.stringify(manifest, null, 2) + '\n').toMatchFileSnapshot(
      '../../command-manifest.json'
    );
  });

  it('every entity-selector option uses the §4.2 SELECTOR_DESCRIPTION phrasing', () => {
    // Selector-phrasing drift arrives through shapes a source grep misses
    // (inline literals, pre-existing named constants, novel phrasings).
    // Grep-by-expected-phrasing cannot prove completeness; walking the LIVE
    // command tree can — this is the structural guard for §4.2.
    const BASES: Record<string, string> = {
      character: SELECTOR_DESCRIPTION.character,
      preset: SELECTOR_DESCRIPTION.preset,
      persona: SELECTOR_DESCRIPTION.persona,
      voice: SELECTOR_DESCRIPTION.voice,
      tts: SELECTOR_DESCRIPTION.ttsConfig,
    };
    // /deny keeps its bespoke wording until its planned redesign rebuilds
    // that surface (raw-ID target + scope-conditional options — a different
    // shape); remove this exemption when it lands.
    const EXEMPT_COMMANDS = new Set(['deny']);

    interface OptionNode {
      type: number;
      name: string;
      description?: string;
      options?: OptionNode[];
    }
    const violations: string[] = [];
    const walk = (options: OptionNode[] | undefined, path: string): void => {
      for (const opt of options ?? []) {
        if (opt.type === 1 || opt.type === 2) {
          walk(opt.options, `${path} ${opt.name}`);
        } else if (opt.name in BASES) {
          const base = BASES[opt.name];
          const desc = opt.description ?? '';
          // Base form, a qualified `${base} — …` clause, or a `${base} (…)`
          // parenthetical are conforming; anything else is drift. GLOBAL
          // preset's "Which global preset" is its own registry entry.
          const ok =
            desc === base ||
            desc.startsWith(`${base} `) ||
            desc === SELECTOR_DESCRIPTION.globalPreset;
          if (!ok) {
            violations.push(`${path} [${opt.name}]: ${desc}`);
          }
        }
      }
    };
    for (const cmd of handler.getCommands().values()) {
      if (EXEMPT_COMMANDS.has(cmd.data.name)) {
        continue;
      }
      const json = cmd.data.toJSON() as { options?: OptionNode[] };
      walk(json.options, `/${cmd.data.name}`);
    }
    expect(violations).toEqual([]);
  });
});
