/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/clients/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

/**
 * Route registration order:
 *
 * `sortRoutesForExpress` in mounts-builder.ts sorts routes ascending by
 * `:param` segment count, so literal paths (e.g., `/voices/clear`)
 * register before parameterized siblings (e.g., `/voices/:provider/:voiceId`).
 * Express matches in registration order, so this guarantees the most
 * specific path wins for any (method, parent) shape collision.
 */

import type { Express } from 'express';
import {
  requireOwnerAuth,
  requireProvisionedUser,
  requireUserAuth,
} from '../../services/AuthMiddleware.js';
import type { RouteDeps } from '../routeDeps.js';

import { handleAiGenerate } from '../ai/generate.js';
import { handleAiTranscribe } from '../ai/transcribe.js';
import { handleAiJobStatus } from '../ai/jobStatus.js';
import { handleAiConfirmDelivery } from '../ai/confirmDelivery.js';
import { handleReleaseBroadcastPending, handleReleaseBroadcastDeliveries } from '../internal/releaseBroadcast.js';
import { handleReleaseBroadcastReconcile } from '../internal/releaseReconcile.js';
import { handleSetDmSession } from '../internal/dmSessionSet.js';
import { handleStampUserActivity } from '../internal/usersActivity.js';
import { handleLookupPersonalityFromMessage } from '../user/conversationLookup.js';
import { handlePersistAssistantMessage } from '../internal/conversationAssistantMessage.js';
import { handlePersistUserMessage } from '../internal/conversationUserMessage.js';
import { handleSyncConversation } from '../internal/conversationSync.js';
import { handleLoadPersonalityInternal } from '../internal/personalityLoad.js';
import { handleRoutingContextCreate } from '../internal/routingContextCreate.js';
import { handleRecentUsers } from '../internal/usersRecent.js';
import { handleSecretRotationStatus } from '../internal/secretRotationStatus.js';
import { handleGetModels } from '../internal/models.js';
import { handleGetDenylistCache, handleAddDenylistEntry, handleListDenylistEntries, handleRemoveDenylistEntry } from '../admin/denylist.js';
import { handleUpdateDiagnosticResponseIds, handleGetRecentDiagnostics, handleGetDiagnosticByMessage, handleGetDiagnosticByResponse, handleGetDiagnosticByRequestId } from '../admin/diagnostic.js';
import { handleGetUserChannel } from '../user/channel/get.js';
import { handleGetAdminSettings, handleUpdateAdminSettings, handleClearAdminSettings } from '../admin/settings.js';
import { handleDbSync } from '../admin/dbSync.js';
import { handleBroadcast } from '../admin/broadcast.js';
import { handleCleanup } from '../admin/cleanup.js';
import { handleInvalidateCache } from '../admin/invalidateCache.js';
import { handleCreateGlobalPersonality } from '../admin/createPersonality.js';
import { handleUpdateGlobalPersonality } from '../admin/updatePersonality.js';
import { handleListGlobalLlmConfigs, handleGetGlobalLlmConfig, handleCreateGlobalLlmConfig, handleUpdateGlobalLlmConfig, handleSetGlobalLlmConfigDefault, handleSetGlobalLlmConfigFreeDefault, handleDeleteGlobalLlmConfig } from '../admin/llm-config.js';
import { handleListGlobalTtsConfigs, handleGetGlobalTtsConfig, handleCreateGlobalTtsConfig, handleUpdateGlobalTtsConfig, handleSetGlobalTtsConfigDefault, handleSetGlobalTtsConfigFreeDefault, handleDeleteGlobalTtsConfig } from '../admin/tts-config.js';
import { handleGetSystemSettings, handleUpdateSystemSettings } from '../admin/systemSettings.js';
import { handleGetAdminUsageStats } from '../admin/usage.js';
import { handleStartAccountExport, handleGetAccountExportStatus } from '../user/account/export.js';
import { handlePreviewAccountDelete, handleIssueAccountDeleteToken, handleDeleteAccount } from '../user/account/delete.js';
import { handleSubmitFeedback } from '../user/feedback.js';
import { handleGetTimezone, handleSetTimezone } from '../user/timezone.js';
import { handleGetNotificationPrefs, handleUpdateNotificationPrefs, handleListReleaseDms, handleMarkReleaseDmsDeleted } from '../user/notifications.js';
import { handleListUserLlmConfigs, handleGetUserLlmConfig, handleCreateUserLlmConfig, handleUpdateUserLlmConfig, handleDeleteUserLlmConfig, handleResolveUserLlmConfig } from '../user/llm-config.js';
import { handleListUserTtsConfigs, handleGetUserTtsConfig, handleCreateUserTtsConfig, handleUpdateUserTtsConfig, handleDeleteUserTtsConfig } from '../user/tts-config.js';
import { handleListTtsOverrides, handleSetTtsOverride, handleDeleteTtsOverride, handleGetTtsDefaultConfig, handleSetTtsDefaultConfig, handleClearTtsDefaultConfig } from '../user/tts-override.js';
import { handleGetSttDefaultProvider, handleSetSttDefaultProvider, handleClearSttDefaultProvider } from '../user/stt-override.js';
import { handleListModelOverrides, handleSetModelOverride, handleDeleteModelOverride, handleGetDefaultModelConfig, handleSetDefaultModelConfig, handleClearDefaultModelConfig } from '../user/model-override.js';
import { handleListPersonalities } from '../user/personality/list.js';
import { handleGetPersonality } from '../user/personality/get.js';
import { handleCreatePersonality } from '../user/personality/create.js';
import { handleUpdatePersonality } from '../user/personality/update.js';
import { handleSetPersonalityVisibility } from '../user/personality/visibility.js';
import { handleDeletePersonality } from '../user/personality/delete.js';
import { handleListPersonalityAliases, handleAddPersonalityAlias, handleRemovePersonalityAlias, handleListMyAliases } from '../user/personality/aliases.js';
import { handleListPersonas, handleGetPersona, handleCreatePersona, handleUpdatePersona, handleDeletePersona } from '../user/persona/crud.js';
import { handleSetPersonaDefault } from '../user/persona/default.js';
import { handleListPersonaOverrides, handleGetPersonaOverride, handleSetPersonaOverride, handleClearPersonaOverride, handleCreatePersonaOverride } from '../user/persona/override.js';
import { handleActivateChannel } from '../user/channel/activate.js';
import { handleDeactivateChannel } from '../user/channel/deactivate.js';
import { handleListUserChannels } from '../user/channel/list.js';
import { handleUpdateChannelGuild } from '../user/channel/updateGuild.js';
import { handleGetChannelConfigOverrides, handleUpdateChannelConfigOverrides, handleClearChannelConfigOverrides } from '../user/channel/configOverrides.js';
import { handleGetUserUsage } from '../user/usage.js';
import { handleClearHistory, handleUndoHistory, handleGetHistoryStats, handleHardDeleteHistory } from '../user/history.js';
import { handleGetNsfwStatus, handleVerifyNsfw } from '../user/nsfw.js';
import { handleListWalletKeys } from '../wallet/listKeys.js';
import { handleSetWalletKey } from '../wallet/setKey.js';
import { handleRemoveWalletKey } from '../wallet/removeKey.js';
import { handleTestWalletKey } from '../wallet/testKey.js';
import { handleGetVoiceResolution } from '../user/voice-resolution.js';
import { handleListVoices, handleListVoiceModels, handleClearVoices, handleDeleteVoice } from '../user/voices.js';
import { handleGetStats } from '../user/memory.js';
import { handleList } from '../user/memoryList.js';
import { handleSearch } from '../user/memorySearch.js';
import { handleBatchDeletePreview, handleBatchDelete, handleIssuePurgeToken, handlePurge } from '../user/memoryBatch.js';
import { handleGetMemory, handleUpdateMemory, handleDeleteMemory, handleSetMemoryLock } from '../user/memorySingle.js';
import { handleGetIncognitoStatus, handleEnableIncognito, handleDisableIncognito, handleIncognitoForget } from '../user/memoryIncognito.js';
import { handleGetFreshStatus, handleEnableFresh, handleDisableFresh } from '../user/memoryFresh.js';
import { handleListFacts, handleGetFact, handleCorrectFact, handleForgetFact, handleSetFactLock } from '../user/memoryFacts.js';
import { handleResolveUserDefaults, handleGetUserDefaults, handleUpdateUserDefaults, handleClearUserDefaults, handleResolveCascade, handleUpdatePersonalityOverrides, handleClearPersonalityOverrides } from '../user/config-overrides.js';
import { handleResolvePersonalityCascade, handleUpdatePersonalityConfigDefaults } from '../user/personality-config-overrides.js';
import { handleStoreShapesAuth, handleDeleteShapesAuth, handleGetShapesAuthStatus } from '../user/shapes/auth.js';
import { handleListShapes } from '../user/shapes/list.js';
import { handleStartShapesImport, handleListShapesImportJobs } from '../user/shapes/import.js';
import { handleStartShapesExport, handleListShapesExportJobs } from '../user/shapes/export.js';

export function mountInternalRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/internal/ai/generate', handleAiGenerate(deps));
  app.post('/api/internal/ai/transcribe', handleAiTranscribe(deps));
  app.post('/api/internal/release-broadcast/reconcile', handleReleaseBroadcastReconcile(deps));
  app.post('/api/internal/channel/dm-session/set', handleSetDmSession(deps));
  app.post('/api/internal/users/activity', handleStampUserActivity(deps));
  app.get('/api/internal/conversation/message-personality', handleLookupPersonalityFromMessage(deps));
  app.post('/api/internal/conversation/assistant-message', handlePersistAssistantMessage(deps));
  app.post('/api/internal/conversation/user-message', handlePersistUserMessage(deps));
  app.post('/api/internal/conversation/sync', handleSyncConversation(deps));
  app.get('/api/internal/personality/load', handleLoadPersonalityInternal(deps));
  app.post('/api/internal/v1/routing-context', handleRoutingContextCreate(deps));
  app.get('/api/internal/users/recent', handleRecentUsers(deps));
  app.get('/api/internal/secret-rotations', handleSecretRotationStatus(deps));
  app.get('/api/internal/models', handleGetModels(deps));
  app.get('/api/internal/denylist/cache', handleGetDenylistCache(deps));
  app.get('/api/internal/admin-settings', handleGetAdminSettings(deps));
  app.get('/api/internal/ai/job/:jobId', handleAiJobStatus(deps));
  app.post('/api/internal/ai/job/:jobId/confirm-delivery', handleAiConfirmDelivery(deps));
  app.post('/api/internal/release-broadcast/:releaseId/pending', handleReleaseBroadcastPending(deps));
  app.post('/api/internal/release-broadcast/:releaseId/deliveries', handleReleaseBroadcastDeliveries(deps));
  app.patch('/api/internal/diagnostic/:requestId/response-ids', handleUpdateDiagnosticResponseIds(deps));
  app.get('/api/internal/channel/:channelId', handleGetUserChannel(deps));
}

export function mountAdminRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/admin/db-sync', requireUserAuth(), requireOwnerAuth(), handleDbSync(deps));
  app.post('/api/admin/broadcast', requireUserAuth(), requireOwnerAuth(), handleBroadcast(deps));
  app.post('/api/admin/cleanup', requireUserAuth(), requireOwnerAuth(), handleCleanup(deps));
  app.post('/api/admin/invalidate-cache', requireUserAuth(), requireOwnerAuth(), handleInvalidateCache(deps));
  app.post('/api/admin/personality', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalPersonality(deps));
  app.post('/api/admin/denylist', requireUserAuth(), requireOwnerAuth(), handleAddDenylistEntry(deps));
  app.get('/api/admin/denylist', requireUserAuth(), requireOwnerAuth(), handleListDenylistEntries(deps));
  app.get('/api/admin/llm-config', requireUserAuth(), requireOwnerAuth(), handleListGlobalLlmConfigs(deps));
  app.post('/api/admin/llm-config', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalLlmConfig(deps));
  app.get('/api/admin/tts-config', requireUserAuth(), requireOwnerAuth(), handleListGlobalTtsConfigs(deps));
  app.post('/api/admin/tts-config', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalTtsConfig(deps));
  app.get('/api/admin/settings', requireUserAuth(), requireOwnerAuth(), handleGetAdminSettings(deps));
  app.patch('/api/admin/settings/config-defaults', requireUserAuth(), requireOwnerAuth(), handleUpdateAdminSettings(deps));
  app.get('/api/admin/settings/system', requireUserAuth(), requireOwnerAuth(), handleGetSystemSettings(deps));
  app.patch('/api/admin/settings/system', requireUserAuth(), requireOwnerAuth(), handleUpdateSystemSettings(deps));
  app.delete('/api/admin/settings/config-defaults', requireUserAuth(), requireOwnerAuth(), handleClearAdminSettings(deps));
  app.get('/api/admin/usage', requireUserAuth(), requireOwnerAuth(), handleGetAdminUsageStats(deps));
  app.patch('/api/admin/personality/:slug', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalPersonality(deps));
  app.get('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleGetGlobalLlmConfig(deps));
  app.put('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalLlmConfig(deps));
  app.put('/api/admin/llm-config/:id/set-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalLlmConfigDefault(deps));
  app.put('/api/admin/llm-config/:id/set-free-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalLlmConfigFreeDefault(deps));
  app.delete('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleDeleteGlobalLlmConfig(deps));
  app.get('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleGetGlobalTtsConfig(deps));
  app.put('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalTtsConfig(deps));
  app.put('/api/admin/tts-config/:id/set-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalTtsConfigDefault(deps));
  app.put('/api/admin/tts-config/:id/set-free-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalTtsConfigFreeDefault(deps));
  app.delete('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleDeleteGlobalTtsConfig(deps));
  app.delete('/api/admin/denylist/:type/:discordId/:scope/:scopeId', requireUserAuth(), requireOwnerAuth(), handleRemoveDenylistEntry(deps));
}

export function mountUserRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/user/account/export', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStartAccountExport(deps));
  app.get('/api/user/account/export/status', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetAccountExportStatus(deps));
  app.get('/api/user/account/delete/preview', requireUserAuth(), requireProvisionedUser(deps.prisma), handlePreviewAccountDelete(deps));
  app.post('/api/user/account/delete/token', requireUserAuth(), requireProvisionedUser(deps.prisma), handleIssueAccountDeleteToken(deps));
  app.post('/api/user/account/delete', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteAccount(deps));
  app.post('/api/user/feedback', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSubmitFeedback(deps));
  app.get('/api/user/timezone', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetTimezone(deps));
  app.put('/api/user/timezone', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTimezone(deps));
  app.get('/api/user/notifications', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetNotificationPrefs(deps));
  app.patch('/api/user/notifications', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateNotificationPrefs(deps));
  app.get('/api/user/notifications/release-dms', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListReleaseDms(deps));
  app.post('/api/user/notifications/release-dms/deleted', requireUserAuth(), requireProvisionedUser(deps.prisma), handleMarkReleaseDmsDeleted(deps));
  app.get('/api/user/llm-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserLlmConfigs(deps));
  app.post('/api/user/llm-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreateUserLlmConfig(deps));
  app.post('/api/user/llm-config/resolve', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolveUserLlmConfig(deps));
  app.get('/api/user/tts-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserTtsConfigs(deps));
  app.post('/api/user/tts-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreateUserTtsConfig(deps));
  app.get('/api/user/tts-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListTtsOverrides(deps));
  app.put('/api/user/tts-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTtsOverride(deps));
  app.get('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetTtsDefaultConfig(deps));
  app.put('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTtsDefaultConfig(deps));
  app.delete('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearTtsDefaultConfig(deps));
  app.get('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetSttDefaultProvider(deps));
  app.put('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetSttDefaultProvider(deps));
  app.delete('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearSttDefaultProvider(deps));
  app.get('/api/user/model-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListModelOverrides(deps));
  app.put('/api/user/model-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetModelOverride(deps));
  app.get('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetDefaultModelConfig(deps));
  app.put('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetDefaultModelConfig(deps));
  app.delete('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearDefaultModelConfig(deps));
  app.get('/api/user/personality', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonalities(deps));
  app.post('/api/user/personality', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersonality(deps));
  app.get('/api/user/personality/my-aliases', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListMyAliases(deps));
  app.get('/api/user/persona', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonas(deps));
  app.post('/api/user/persona', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersona(deps));
  app.get('/api/user/persona/override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonaOverrides(deps));
  app.post('/api/user/channel/activate', requireUserAuth(), requireProvisionedUser(deps.prisma), handleActivateChannel(deps));
  app.delete('/api/user/channel/deactivate', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeactivateChannel(deps));
  app.get('/api/user/channel/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserChannels(deps));
  app.patch('/api/user/channel/update-guild', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateChannelGuild(deps));
  app.get('/api/user/usage', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserUsage(deps));
  app.post('/api/user/history/clear', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearHistory(deps));
  app.post('/api/user/history/undo', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUndoHistory(deps));
  app.get('/api/user/history/stats', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetHistoryStats(deps));
  app.delete('/api/user/history/hard-delete', requireUserAuth(), requireProvisionedUser(deps.prisma), handleHardDeleteHistory(deps));
  app.get('/api/user/nsfw', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetNsfwStatus(deps));
  app.post('/api/user/nsfw/verify', requireUserAuth(), requireProvisionedUser(deps.prisma), handleVerifyNsfw(deps));
  app.get('/api/user/wallet/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListWalletKeys(deps));
  app.post('/api/user/wallet/set', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetWalletKey(deps));
  app.post('/api/user/wallet/test', requireUserAuth(), requireProvisionedUser(deps.prisma), handleTestWalletKey(deps));
  app.get('/api/user/voice-resolution', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetVoiceResolution(deps));
  app.get('/api/user/voices', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListVoices(deps));
  app.get('/api/user/voices/models', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListVoiceModels(deps));
  app.post('/api/user/voices/clear', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearVoices(deps));
  app.get('/api/user/memory/stats', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetStats(deps));
  app.get('/api/user/memory/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleList(deps));
  app.post('/api/user/memory/search', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSearch(deps));
  app.post('/api/user/memory/delete/preview', requireUserAuth(), requireProvisionedUser(deps.prisma), handleBatchDeletePreview(deps));
  app.post('/api/user/memory/delete', requireUserAuth(), requireProvisionedUser(deps.prisma), handleBatchDelete(deps));
  app.post('/api/user/memory/purge/token', requireUserAuth(), requireProvisionedUser(deps.prisma), handleIssuePurgeToken(deps));
  app.post('/api/user/memory/purge', requireUserAuth(), requireProvisionedUser(deps.prisma), handlePurge(deps));
  app.get('/api/user/memory/incognito', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetIncognitoStatus(deps));
  app.post('/api/user/memory/incognito', requireUserAuth(), requireProvisionedUser(deps.prisma), handleEnableIncognito(deps));
  app.delete('/api/user/memory/incognito', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDisableIncognito(deps));
  app.post('/api/user/memory/incognito/forget', requireUserAuth(), requireProvisionedUser(deps.prisma), handleIncognitoForget(deps));
  app.get('/api/user/memory/fresh', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetFreshStatus(deps));
  app.post('/api/user/memory/fresh', requireUserAuth(), requireProvisionedUser(deps.prisma), handleEnableFresh(deps));
  app.delete('/api/user/memory/fresh', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDisableFresh(deps));
  app.get('/api/user/fact/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListFacts(deps));
  app.get('/api/user/config-overrides/resolve-defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolveUserDefaults(deps));
  app.get('/api/user/config-overrides/defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserDefaults(deps));
  app.patch('/api/user/config-overrides/defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserDefaults(deps));
  app.delete('/api/user/config-overrides/defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearUserDefaults(deps));
  app.post('/api/user/shapes/auth', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStoreShapesAuth(deps));
  app.delete('/api/user/shapes/auth', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteShapesAuth(deps));
  app.get('/api/user/shapes/auth/status', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetShapesAuthStatus(deps));
  app.get('/api/user/shapes/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListShapes(deps));
  app.post('/api/user/shapes/import', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStartShapesImport(deps));
  app.get('/api/user/shapes/import/jobs', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListShapesImportJobs(deps));
  app.post('/api/user/shapes/export', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStartShapesExport(deps));
  app.get('/api/user/shapes/export/jobs', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListShapesExportJobs(deps));
  app.get('/api/user/diagnostic/recent', requireUserAuth(), handleGetRecentDiagnostics(deps));
  app.get('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserLlmConfig(deps));
  app.put('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserLlmConfig(deps));
  app.delete('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteUserLlmConfig(deps));
  app.get('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserTtsConfig(deps));
  app.put('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserTtsConfig(deps));
  app.delete('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteUserTtsConfig(deps));
  app.delete('/api/user/tts-override/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteTtsOverride(deps));
  app.delete('/api/user/model-override/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteModelOverride(deps));
  app.get('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersonality(deps));
  app.put('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonality(deps));
  app.patch('/api/user/personality/:slug/visibility', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonalityVisibility(deps));
  app.delete('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeletePersonality(deps));
  app.get('/api/user/personality/:slug/aliases', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonalityAliases(deps));
  app.post('/api/user/personality/:slug/aliases', requireUserAuth(), requireProvisionedUser(deps.prisma), handleAddPersonalityAlias(deps));
  app.get('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersona(deps));
  app.put('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersona(deps));
  app.delete('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeletePersona(deps));
  app.patch('/api/user/persona/:id/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonaDefault(deps));
  app.get('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersonaOverride(deps));
  app.put('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonaOverride(deps));
  app.delete('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearPersonaOverride(deps));
  app.post('/api/user/persona/override/by-id/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersonaOverride(deps));
  app.get('/api/user/channel/:channelId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserChannel(deps));
  app.get('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetChannelConfigOverrides(deps));
  app.patch('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateChannelConfigOverrides(deps));
  app.delete('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearChannelConfigOverrides(deps));
  app.delete('/api/user/wallet/:provider', requireUserAuth(), requireProvisionedUser(deps.prisma), handleRemoveWalletKey(deps));
  app.get('/api/user/memory/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetMemory(deps));
  app.patch('/api/user/memory/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateMemory(deps));
  app.delete('/api/user/memory/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteMemory(deps));
  app.put('/api/user/memory/:id/lock', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetMemoryLock(deps));
  app.get('/api/user/fact/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetFact(deps));
  app.patch('/api/user/fact/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCorrectFact(deps));
  app.delete('/api/user/fact/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleForgetFact(deps));
  app.put('/api/user/fact/:id/lock', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetFactLock(deps));
  app.get('/api/user/config-overrides/resolve/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolveCascade(deps));
  app.patch('/api/user/config-overrides/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonalityOverrides(deps));
  app.delete('/api/user/config-overrides/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearPersonalityOverrides(deps));
  app.get('/api/user/config-overrides/resolve-personality/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolvePersonalityCascade(deps));
  app.patch('/api/user/config-overrides/personality/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonalityConfigDefaults(deps));
  app.get('/api/user/diagnostic/by-message/:messageId', requireUserAuth(), handleGetDiagnosticByMessage(deps));
  app.get('/api/user/diagnostic/by-response/:messageId', requireUserAuth(), handleGetDiagnosticByResponse(deps));
  app.get('/api/user/diagnostic/:requestId', requireUserAuth(), handleGetDiagnosticByRequestId(deps));
  app.delete('/api/user/personality/:slug/aliases/:alias', requireUserAuth(), requireProvisionedUser(deps.prisma), handleRemovePersonalityAlias(deps));
  app.delete('/api/user/voices/:provider/:voiceId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteVoice(deps));
}
