/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/common-types/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

/**
 * Route registration order:
 *
 * `sortRoutesForExpress` in mounts-builder.ts sorts routes ascending by
 * `:param` segment count, so literal paths (e.g., `/voices/clear`)
 * register before parameterized siblings (e.g., `/voices/:provider/:voiceId`).
 * Express matches in registration order, so this guarantees the most
 * specific path wins for any (method, parent) shape collision.
 */

import type { Express } from 'express';
import {
  requireOwnerAuth,
  requireProvisionedUser,
  requireUserAuth,
} from '../../services/AuthMiddleware.js';
import type { RouteDeps } from '../routeDeps.js';

import { handleAiGenerate } from '../ai/generate.js';
import { handleAiTranscribe } from '../ai/transcribe.js';
import { handleAiJobStatus } from '../ai/jobStatus.js';
import { handleAiConfirmDelivery } from '../ai/confirmDelivery.js';
import { handleSetDmSession } from '../internal/dmSessionSet.js';
import { handleLookupPersonalityFromMessage } from '../user/conversationLookup.js';
import { handleRecentUsers } from '../internal/usersRecent.js';
import { handleGetDenylistCache } from '../admin/denylist.js';
import { handleUpdateDiagnosticResponseIds } from '../admin/diagnostic.js';
import { handleGetUserChannel } from '../user/channel/get.js';
import { handleGetAdminSettings } from '../admin/settings.js';
import { handleDbSync } from '../admin/dbSync.js';
import { handleCleanup } from '../admin/cleanup.js';
import { handleInvalidateCache } from '../admin/invalidateCache.js';
import { handleCreateGlobalPersonality } from '../admin/createPersonality.js';
import { handleUpdateGlobalPersonality } from '../admin/updatePersonality.js';
import { handleAddDenylistEntry } from '../admin/denylist.js';
import { handleListDenylistEntries } from '../admin/denylist.js';
import { handleRemoveDenylistEntry } from '../admin/denylist.js';
import { handleListGlobalLlmConfigs } from '../admin/llm-config.js';
import { handleGetGlobalLlmConfig } from '../admin/llm-config.js';
import { handleCreateGlobalLlmConfig } from '../admin/llm-config.js';
import { handleUpdateGlobalLlmConfig } from '../admin/llm-config.js';
import { handleSetGlobalLlmConfigDefault } from '../admin/llm-config.js';
import { handleSetGlobalLlmConfigFreeDefault } from '../admin/llm-config.js';
import { handleDeleteGlobalLlmConfig } from '../admin/llm-config.js';
import { handleListGlobalTtsConfigs } from '../admin/tts-config.js';
import { handleGetGlobalTtsConfig } from '../admin/tts-config.js';
import { handleCreateGlobalTtsConfig } from '../admin/tts-config.js';
import { handleUpdateGlobalTtsConfig } from '../admin/tts-config.js';
import { handleSetGlobalTtsConfigDefault } from '../admin/tts-config.js';
import { handleSetGlobalTtsConfigFreeDefault } from '../admin/tts-config.js';
import { handleDeleteGlobalTtsConfig } from '../admin/tts-config.js';
import { handleUpdateAdminSettings } from '../admin/settings.js';
import { handleClearAdminSettings } from '../admin/settings.js';
import { handleGetStopSequencesStats } from '../admin/stopSequences.js';
import { handleGetAdminUsageStats } from '../admin/usage.js';
import { handleGetTimezone } from '../user/timezone.js';
import { handleSetTimezone } from '../user/timezone.js';
import { handleListUserLlmConfigs } from '../user/llm-config.js';
import { handleGetUserLlmConfig } from '../user/llm-config.js';
import { handleCreateUserLlmConfig } from '../user/llm-config.js';
import { handleUpdateUserLlmConfig } from '../user/llm-config.js';
import { handleDeleteUserLlmConfig } from '../user/llm-config.js';
import { handleResolveUserLlmConfig } from '../user/llm-config.js';
import { handleListUserTtsConfigs } from '../user/tts-config.js';
import { handleGetUserTtsConfig } from '../user/tts-config.js';
import { handleCreateUserTtsConfig } from '../user/tts-config.js';
import { handleUpdateUserTtsConfig } from '../user/tts-config.js';
import { handleDeleteUserTtsConfig } from '../user/tts-config.js';
import { handleListTtsOverrides } from '../user/tts-override.js';
import { handleSetTtsOverride } from '../user/tts-override.js';
import { handleDeleteTtsOverride } from '../user/tts-override.js';
import { handleGetTtsDefaultConfig } from '../user/tts-override.js';
import { handleSetTtsDefaultConfig } from '../user/tts-override.js';
import { handleClearTtsDefaultConfig } from '../user/tts-override.js';
import { handleGetSttDefaultProvider } from '../user/stt-override.js';
import { handleSetSttDefaultProvider } from '../user/stt-override.js';
import { handleClearSttDefaultProvider } from '../user/stt-override.js';
import { handleListModelOverrides } from '../user/model-override.js';
import { handleSetModelOverride } from '../user/model-override.js';
import { handleDeleteModelOverride } from '../user/model-override.js';
import { handleGetDefaultModelConfig } from '../user/model-override.js';
import { handleSetDefaultModelConfig } from '../user/model-override.js';
import { handleClearDefaultModelConfig } from '../user/model-override.js';
import { handleListPersonalities } from '../user/personality/list.js';
import { handleGetPersonality } from '../user/personality/get.js';
import { handleCreatePersonality } from '../user/personality/create.js';
import { handleUpdatePersonality } from '../user/personality/update.js';
import { handleSetPersonalityVisibility } from '../user/personality/visibility.js';
import { handleDeletePersonality } from '../user/personality/delete.js';
import { handleListPersonas } from '../user/persona/crud.js';
import { handleGetPersona } from '../user/persona/crud.js';
import { handleCreatePersona } from '../user/persona/crud.js';
import { handleUpdatePersona } from '../user/persona/crud.js';
import { handleDeletePersona } from '../user/persona/crud.js';
import { handleSetPersonaDefault } from '../user/persona/default.js';
import { handleListPersonaOverrides } from '../user/persona/override.js';
import { handleGetPersonaOverride } from '../user/persona/override.js';
import { handleSetPersonaOverride } from '../user/persona/override.js';
import { handleClearPersonaOverride } from '../user/persona/override.js';
import { handleCreatePersonaOverride } from '../user/persona/override.js';
import { handleActivateChannel } from '../user/channel/activate.js';
import { handleDeactivateChannel } from '../user/channel/deactivate.js';
import { handleListUserChannels } from '../user/channel/list.js';
import { handleUpdateChannelGuild } from '../user/channel/updateGuild.js';
import { handleGetChannelConfigOverrides } from '../user/channel/configOverrides.js';
import { handleUpdateChannelConfigOverrides } from '../user/channel/configOverrides.js';
import { handleClearChannelConfigOverrides } from '../user/channel/configOverrides.js';
import { handleGetUserUsage } from '../user/usage.js';
import { handleClearHistory } from '../user/history.js';
import { handleUndoHistory } from '../user/history.js';
import { handleGetHistoryStats } from '../user/history.js';
import { handleHardDeleteHistory } from '../user/history.js';
import { handleGetNsfwStatus } from '../user/nsfw.js';
import { handleVerifyNsfw } from '../user/nsfw.js';
import { handleListWalletKeys } from '../wallet/listKeys.js';
import { handleSetWalletKey } from '../wallet/setKey.js';
import { handleRemoveWalletKey } from '../wallet/removeKey.js';
import { handleTestWalletKey } from '../wallet/testKey.js';
import { handleGetVoiceResolution } from '../user/voice-resolution.js';
import { handleListVoices } from '../user/voices.js';
import { handleListVoiceModels } from '../user/voices.js';
import { handleClearVoices } from '../user/voices.js';
import { handleDeleteVoice } from '../user/voices.js';
import { handleGetStats } from '../user/memory.js';
import { handleList } from '../user/memoryList.js';
import { handleGetFocus } from '../user/memory.js';
import { handleSetFocus } from '../user/memory.js';
import { handleSearch } from '../user/memorySearch.js';
import { handleBatchDeletePreview } from '../user/memoryBatch.js';
import { handleBatchDelete } from '../user/memoryBatch.js';
import { handleIssuePurgeToken } from '../user/memoryBatch.js';
import { handlePurge } from '../user/memoryBatch.js';
import { handleGetMemory } from '../user/memorySingle.js';
import { handleUpdateMemory } from '../user/memorySingle.js';
import { handleDeleteMemory } from '../user/memorySingle.js';
import { handleSetMemoryLock } from '../user/memorySingle.js';
import { handleGetIncognitoStatus } from '../user/memoryIncognito.js';
import { handleEnableIncognito } from '../user/memoryIncognito.js';
import { handleDisableIncognito } from '../user/memoryIncognito.js';
import { handleIncognitoForget } from '../user/memoryIncognito.js';
import { handleResolveUserDefaults } from '../user/config-overrides.js';
import { handleGetUserDefaults } from '../user/config-overrides.js';
import { handleUpdateUserDefaults } from '../user/config-overrides.js';
import { handleClearUserDefaults } from '../user/config-overrides.js';
import { handleResolveCascade } from '../user/config-overrides.js';
import { handleUpdatePersonalityOverrides } from '../user/config-overrides.js';
import { handleClearPersonalityOverrides } from '../user/config-overrides.js';
import { handleResolvePersonalityCascade } from '../user/personality-config-overrides.js';
import { handleUpdatePersonalityConfigDefaults } from '../user/personality-config-overrides.js';
import { handleStoreShapesAuth } from '../user/shapes/auth.js';
import { handleDeleteShapesAuth } from '../user/shapes/auth.js';
import { handleGetShapesAuthStatus } from '../user/shapes/auth.js';
import { handleListShapes } from '../user/shapes/list.js';
import { handleStartShapesImport } from '../user/shapes/import.js';
import { handleListShapesImportJobs } from '../user/shapes/import.js';
import { handleStartShapesExport } from '../user/shapes/export.js';
import { handleListShapesExportJobs } from '../user/shapes/export.js';
import { handleGetRecentDiagnostics } from '../admin/diagnostic.js';
import { handleGetDiagnosticByMessage } from '../admin/diagnostic.js';
import { handleGetDiagnosticByResponse } from '../admin/diagnostic.js';
import { handleGetDiagnosticByRequestId } from '../admin/diagnostic.js';

export function mountInternalRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/internal/ai/generate', handleAiGenerate(deps));
  app.post('/api/internal/ai/transcribe', handleAiTranscribe(deps));
  app.post('/api/internal/channel/dm-session/set', handleSetDmSession(deps));
  app.get('/api/internal/conversation/message-personality', handleLookupPersonalityFromMessage(deps));
  app.get('/api/internal/users/recent', handleRecentUsers(deps));
  app.get('/api/internal/denylist/cache', handleGetDenylistCache(deps));
  app.get('/api/internal/admin-settings', handleGetAdminSettings(deps));
  app.get('/api/internal/ai/job/:jobId', handleAiJobStatus(deps));
  app.post('/api/internal/ai/job/:jobId/confirm-delivery', handleAiConfirmDelivery(deps));
  app.patch('/api/internal/diagnostic/:requestId/response-ids', handleUpdateDiagnosticResponseIds(deps));
  app.get('/api/internal/channel/:channelId', handleGetUserChannel(deps));
}

export function mountAdminRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/admin/db-sync', requireUserAuth(), requireOwnerAuth(), handleDbSync(deps));
  app.post('/api/admin/cleanup', requireUserAuth(), requireOwnerAuth(), handleCleanup(deps));
  app.post('/api/admin/invalidate-cache', requireUserAuth(), requireOwnerAuth(), handleInvalidateCache(deps));
  app.post('/api/admin/personality', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalPersonality(deps));
  app.post('/api/admin/denylist', requireUserAuth(), requireOwnerAuth(), handleAddDenylistEntry(deps));
  app.get('/api/admin/denylist', requireUserAuth(), requireOwnerAuth(), handleListDenylistEntries(deps));
  app.get('/api/admin/llm-config', requireUserAuth(), requireOwnerAuth(), handleListGlobalLlmConfigs(deps));
  app.post('/api/admin/llm-config', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalLlmConfig(deps));
  app.get('/api/admin/tts-config', requireUserAuth(), requireOwnerAuth(), handleListGlobalTtsConfigs(deps));
  app.post('/api/admin/tts-config', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalTtsConfig(deps));
  app.get('/api/admin/settings', requireUserAuth(), requireOwnerAuth(), handleGetAdminSettings(deps));
  app.patch('/api/admin/settings/config-defaults', requireUserAuth(), requireOwnerAuth(), handleUpdateAdminSettings(deps));
  app.delete('/api/admin/settings/config-defaults', requireUserAuth(), requireOwnerAuth(), handleClearAdminSettings(deps));
  app.get('/api/admin/stop-sequences', requireUserAuth(), requireOwnerAuth(), handleGetStopSequencesStats(deps));
  app.get('/api/admin/usage', requireUserAuth(), requireOwnerAuth(), handleGetAdminUsageStats(deps));
  app.patch('/api/admin/personality/:slug', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalPersonality(deps));
  app.get('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleGetGlobalLlmConfig(deps));
  app.put('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalLlmConfig(deps));
  app.put('/api/admin/llm-config/:id/set-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalLlmConfigDefault(deps));
  app.put('/api/admin/llm-config/:id/set-free-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalLlmConfigFreeDefault(deps));
  app.delete('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleDeleteGlobalLlmConfig(deps));
  app.get('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleGetGlobalTtsConfig(deps));
  app.put('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalTtsConfig(deps));
  app.put('/api/admin/tts-config/:id/set-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalTtsConfigDefault(deps));
  app.put('/api/admin/tts-config/:id/set-free-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalTtsConfigFreeDefault(deps));
  app.delete('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleDeleteGlobalTtsConfig(deps));
  app.delete('/api/admin/denylist/:type/:discordId/:scope/:scopeId', requireUserAuth(), requireOwnerAuth(), handleRemoveDenylistEntry(deps));
}

export function mountUserRoutes(app: Express, deps: RouteDeps): void {
  app.get('/api/user/timezone', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetTimezone(deps));
  app.put('/api/user/timezone', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTimezone(deps));
  app.get('/api/user/llm-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserLlmConfigs(deps));
  app.post('/api/user/llm-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreateUserLlmConfig(deps));
  app.post('/api/user/llm-config/resolve', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolveUserLlmConfig(deps));
  app.get('/api/user/tts-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserTtsConfigs(deps));
  app.post('/api/user/tts-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreateUserTtsConfig(deps));
  app.get('/api/user/tts-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListTtsOverrides(deps));
  app.put('/api/user/tts-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTtsOverride(deps));
  app.get('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetTtsDefaultConfig(deps));
  app.put('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTtsDefaultConfig(deps));
  app.delete('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearTtsDefaultConfig(deps));
  app.get('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetSttDefaultProvider(deps));
  app.put('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetSttDefaultProvider(deps));
  app.delete('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearSttDefaultProvider(deps));
  app.get('/api/user/model-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListModelOverrides(deps));
  app.put('/api/user/model-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetModelOverride(deps));
  app.get('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetDefaultModelConfig(deps));
  app.put('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetDefaultModelConfig(deps));
  app.delete('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearDefaultModelConfig(deps));
  app.get('/api/user/personality', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonalities(deps));
  app.post('/api/user/personality', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersonality(deps));
  app.get('/api/user/persona', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonas(deps));
  app.post('/api/user/persona', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersona(deps));
  app.get('/api/user/persona/override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonaOverrides(deps));
  app.post('/api/user/channel/activate', requireUserAuth(), requireProvisionedUser(deps.prisma), handleActivateChannel(deps));
  app.delete('/api/user/channel/deactivate', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeactivateChannel(deps));
  app.get('/api/user/channel/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserChannels(deps));
  app.patch('/api/user/channel/update-guild', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateChannelGuild(deps));
  app.get('/api/user/usage', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserUsage(deps));
  app.post('/api/user/history/clear', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearHistory(deps));
  app.post('/api/user/history/undo', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUndoHistory(deps));
  app.get('/api/user/history/stats', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetHistoryStats(deps));
  app.delete('/api/user/history/hard-delete', requireUserAuth(), requireProvisionedUser(deps.prisma), handleHardDeleteHistory(deps));
  app.get('/api/user/nsfw', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetNsfwStatus(deps));
  app.post('/api/user/nsfw/verify', requireUserAuth(), requireProvisionedUser(deps.prisma), handleVerifyNsfw(deps));
  app.get('/api/user/wallet/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListWalletKeys(deps));
  app.post('/api/user/wallet/set', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetWalletKey(deps));
  app.post('/api/user/wallet/test', requireUserAuth(), requireProvisionedUser(deps.prisma), handleTestWalletKey(deps));
  app.get('/api/user/voice-resolution', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetVoiceResolution(deps));
  app.get('/api/user/voices', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListVoices(deps));
  app.get('/api/user/voices/models', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListVoiceModels(deps));
  app.post('/api/user/voices/clear', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearVoices(deps));
  app.get('/api/user/memory/stats', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetStats(deps));
  app.get('/api/user/memory/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleList(deps));
  app.get('/api/user/memory/focus', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetFocus(deps));
  app.post('/api/user/memory/focus', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetFocus(deps));
  app.post('/api/user/memory/search', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSearch(deps));
  app.post('/api/user/memory/delete/preview', requireUserAuth(), requireProvisionedUser(deps.prisma), handleBatchDeletePreview(deps));
  app.post('/api/user/memory/delete', requireUserAuth(), requireProvisionedUser(deps.prisma), handleBatchDelete(deps));
  app.post('/api/user/memory/purge/token', requireUserAuth(), requireProvisionedUser(deps.prisma), handleIssuePurgeToken(deps));
  app.post('/api/user/memory/purge', requireUserAuth(), requireProvisionedUser(deps.prisma), handlePurge(deps));
  app.get('/api/user/memory/incognito', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetIncognitoStatus(deps));
  app.post('/api/user/memory/incognito', requireUserAuth(), requireProvisionedUser(deps.prisma), handleEnableIncognito(deps));
  app.delete('/api/user/memory/incognito', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDisableIncognito(deps));
  app.post('/api/user/memory/incognito/forget', requireUserAuth(), requireProvisionedUser(deps.prisma), handleIncognitoForget(deps));
  app.get('/api/user/config-overrides/resolve-defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolveUserDefaults(deps));
  app.get('/api/user/config-overrides/defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserDefaults(deps));
  app.patch('/api/user/config-overrides/defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserDefaults(deps));
  app.delete('/api/user/config-overrides/defaults', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearUserDefaults(deps));
  app.post('/api/user/shapes/auth', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStoreShapesAuth(deps));
  app.delete('/api/user/shapes/auth', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteShapesAuth(deps));
  app.get('/api/user/shapes/auth/status', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetShapesAuthStatus(deps));
  app.get('/api/user/shapes/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListShapes(deps));
  app.post('/api/user/shapes/import', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStartShapesImport(deps));
  app.get('/api/user/shapes/import/jobs', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListShapesImportJobs(deps));
  app.post('/api/user/shapes/export', requireUserAuth(), requireProvisionedUser(deps.prisma), handleStartShapesExport(deps));
  app.get('/api/user/shapes/export/jobs', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListShapesExportJobs(deps));
  app.get('/api/user/diagnostic/recent', requireUserAuth(), handleGetRecentDiagnostics(deps));
  app.get('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserLlmConfig(deps));
  app.put('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserLlmConfig(deps));
  app.delete('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteUserLlmConfig(deps));
  app.get('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserTtsConfig(deps));
  app.put('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserTtsConfig(deps));
  app.delete('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteUserTtsConfig(deps));
  app.delete('/api/user/tts-override/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteTtsOverride(deps));
  app.delete('/api/user/model-override/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteModelOverride(deps));
  app.get('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersonality(deps));
  app.put('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonality(deps));
  app.patch('/api/user/personality/:slug/visibility', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonalityVisibility(deps));
  app.delete('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeletePersonality(deps));
  app.get('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersona(deps));
  app.put('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersona(deps));
  app.delete('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeletePersona(deps));
  app.patch('/api/user/persona/:id/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonaDefault(deps));
  app.get('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersonaOverride(deps));
  app.put('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonaOverride(deps));
  app.delete('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearPersonaOverride(deps));
  app.post('/api/user/persona/override/by-id/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersonaOverride(deps));
  app.get('/api/user/channel/:channelId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserChannel(deps));
  app.get('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetChannelConfigOverrides(deps));
  app.patch('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateChannelConfigOverrides(deps));
  app.delete('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearChannelConfigOverrides(deps));
  app.delete('/api/user/wallet/:provider', requireUserAuth(), requireProvisionedUser(deps.prisma), handleRemoveWalletKey(deps));
  app.get('/api/user/memory/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetMemory(deps));
  app.patch('/api/user/memory/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateMemory(deps));
  app.delete('/api/user/memory/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteMemory(deps));
  app.put('/api/user/memory/:id/lock', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetMemoryLock(deps));
  app.get('/api/user/config-overrides/resolve/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolveCascade(deps));
  app.patch('/api/user/config-overrides/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonalityOverrides(deps));
  app.delete('/api/user/config-overrides/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearPersonalityOverrides(deps));
  app.get('/api/user/config-overrides/resolve-personality/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleResolvePersonalityCascade(deps));
  app.patch('/api/user/config-overrides/personality/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonalityConfigDefaults(deps));
  app.get('/api/user/diagnostic/by-message/:messageId', requireUserAuth(), handleGetDiagnosticByMessage(deps));
  app.get('/api/user/diagnostic/by-response/:messageId', requireUserAuth(), handleGetDiagnosticByResponse(deps));
  app.get('/api/user/diagnostic/:requestId', requireUserAuth(), handleGetDiagnosticByRequestId(deps));
  app.delete('/api/user/voices/:provider/:voiceId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteVoice(deps));
}
