/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/common-types/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

import type { Express } from 'express';
import {
  requireOwnerAuth,
  requireProvisionedUser,
  requireUserAuth,
} from '../../services/AuthMiddleware.js';
import type { RouteDeps } from '../routeDeps.js';

import { handleAiGenerate } from '../ai/generate.js';
import { handleAiTranscribe } from '../ai/transcribe.js';
import { handleAiJobStatus } from '../ai/jobStatus.js';
import { handleAiConfirmDelivery } from '../ai/confirmDelivery.js';
import { handleSetDmSession } from '../internal/dmSessionSet.js';
import { handleLookupPersonalityFromMessage } from '../user/conversationLookup.js';
import { handleRecentUsers } from '../internal/usersRecent.js';
import { handleGetDenylistCache } from '../admin/denylist.js';
import { handleUpdateDiagnosticResponseIds } from '../admin/diagnostic.js';
import { handleGetUserChannel } from '../user/channel/get.js';
import { handleDbSync } from '../admin/dbSync.js';
import { handleCleanup } from '../admin/cleanup.js';
import { handleInvalidateCache } from '../admin/invalidateCache.js';
import { handleCreateGlobalPersonality } from '../admin/createPersonality.js';
import { handleUpdateGlobalPersonality } from '../admin/updatePersonality.js';
import { handleAddDenylistEntry } from '../admin/denylist.js';
import { handleListDenylistEntries } from '../admin/denylist.js';
import { handleRemoveDenylistEntry } from '../admin/denylist.js';
import { handleListGlobalLlmConfigs } from '../admin/llm-config.js';
import { handleGetGlobalLlmConfig } from '../admin/llm-config.js';
import { handleCreateGlobalLlmConfig } from '../admin/llm-config.js';
import { handleUpdateGlobalLlmConfig } from '../admin/llm-config.js';
import { handleSetGlobalLlmConfigDefault } from '../admin/llm-config.js';
import { handleSetGlobalLlmConfigFreeDefault } from '../admin/llm-config.js';
import { handleDeleteGlobalLlmConfig } from '../admin/llm-config.js';
import { handleListGlobalTtsConfigs } from '../admin/tts-config.js';
import { handleGetGlobalTtsConfig } from '../admin/tts-config.js';
import { handleCreateGlobalTtsConfig } from '../admin/tts-config.js';
import { handleUpdateGlobalTtsConfig } from '../admin/tts-config.js';
import { handleSetGlobalTtsConfigDefault } from '../admin/tts-config.js';
import { handleSetGlobalTtsConfigFreeDefault } from '../admin/tts-config.js';
import { handleDeleteGlobalTtsConfig } from '../admin/tts-config.js';
import { handleGetAdminSettings } from '../admin/settings.js';
import { handleUpdateAdminSettings } from '../admin/settings.js';
import { handleClearAdminSettings } from '../admin/settings.js';
import { handleGetStopSequencesStats } from '../admin/stopSequences.js';
import { handleGetAdminUsageStats } from '../admin/usage.js';
import { handleGetTimezone } from '../user/timezone.js';
import { handleSetTimezone } from '../user/timezone.js';
import { handleListUserLlmConfigs } from '../user/llm-config.js';
import { handleGetUserLlmConfig } from '../user/llm-config.js';
import { handleCreateUserLlmConfig } from '../user/llm-config.js';
import { handleUpdateUserLlmConfig } from '../user/llm-config.js';
import { handleDeleteUserLlmConfig } from '../user/llm-config.js';
import { handleListUserTtsConfigs } from '../user/tts-config.js';
import { handleGetUserTtsConfig } from '../user/tts-config.js';
import { handleCreateUserTtsConfig } from '../user/tts-config.js';
import { handleUpdateUserTtsConfig } from '../user/tts-config.js';
import { handleDeleteUserTtsConfig } from '../user/tts-config.js';
import { handleListTtsOverrides } from '../user/tts-override.js';
import { handleSetTtsOverride } from '../user/tts-override.js';
import { handleDeleteTtsOverride } from '../user/tts-override.js';
import { handleGetTtsDefaultConfig } from '../user/tts-override.js';
import { handleSetTtsDefaultConfig } from '../user/tts-override.js';
import { handleClearTtsDefaultConfig } from '../user/tts-override.js';
import { handleGetSttDefaultProvider } from '../user/stt-override.js';
import { handleSetSttDefaultProvider } from '../user/stt-override.js';
import { handleClearSttDefaultProvider } from '../user/stt-override.js';
import { handleListModelOverrides } from '../user/model-override.js';
import { handleSetModelOverride } from '../user/model-override.js';
import { handleDeleteModelOverride } from '../user/model-override.js';
import { handleGetDefaultModelConfig } from '../user/model-override.js';
import { handleSetDefaultModelConfig } from '../user/model-override.js';
import { handleClearDefaultModelConfig } from '../user/model-override.js';
import { handleListPersonalities } from '../user/personality/list.js';
import { handleGetPersonality } from '../user/personality/get.js';
import { handleCreatePersonality } from '../user/personality/create.js';
import { handleUpdatePersonality } from '../user/personality/update.js';
import { handleSetPersonalityVisibility } from '../user/personality/visibility.js';
import { handleDeletePersonality } from '../user/personality/delete.js';
import { handleListPersonas } from '../user/persona/crud.js';
import { handleGetPersona } from '../user/persona/crud.js';
import { handleCreatePersona } from '../user/persona/crud.js';
import { handleSetPersonaDefault } from '../user/persona/default.js';
import { handleListPersonaOverrides } from '../user/persona/override.js';
import { handleGetPersonaOverride } from '../user/persona/override.js';
import { handleSetPersonaOverride } from '../user/persona/override.js';
import { handleClearPersonaOverride } from '../user/persona/override.js';
import { handleActivateChannel } from '../user/channel/activate.js';
import { handleDeactivateChannel } from '../user/channel/deactivate.js';
import { handleListUserChannels } from '../user/channel/list.js';
import { handleUpdateChannelGuild } from '../user/channel/updateGuild.js';
import { handleGetChannelConfigOverrides } from '../user/channel/configOverrides.js';
import { handleListWalletKeys } from '../wallet/listKeys.js';
import { handleRemoveWalletKey } from '../wallet/removeKey.js';
import { handleTestWalletKey } from '../wallet/testKey.js';
import { handleGetVoiceResolution } from '../user/voice-resolution.js';
import { handleGetRecentDiagnostics } from '../admin/diagnostic.js';
import { handleGetDiagnosticByMessage } from '../admin/diagnostic.js';
import { handleGetDiagnosticByResponse } from '../admin/diagnostic.js';
import { handleGetDiagnosticByRequestId } from '../admin/diagnostic.js';

export function mountInternalRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/internal/ai/generate', handleAiGenerate(deps));
  app.post('/api/internal/ai/transcribe', handleAiTranscribe(deps));
  app.post('/api/internal/channel/dm-session/set', handleSetDmSession(deps));
  app.get('/api/internal/conversation/message-personality', handleLookupPersonalityFromMessage(deps));
  app.get('/api/internal/users/recent', handleRecentUsers(deps));
  app.get('/api/internal/denylist/cache', handleGetDenylistCache(deps));
  app.get('/api/internal/ai/job/:jobId', handleAiJobStatus(deps));
  app.post('/api/internal/ai/job/:jobId/confirm-delivery', handleAiConfirmDelivery(deps));
  app.patch('/api/internal/diagnostic/:requestId/response-ids', handleUpdateDiagnosticResponseIds(deps));
  app.get('/api/internal/channel/:channelId', handleGetUserChannel(deps));
}

export function mountAdminRoutes(app: Express, deps: RouteDeps): void {
  app.post('/api/admin/db-sync', requireUserAuth(), requireOwnerAuth(), handleDbSync(deps));
  app.post('/api/admin/cleanup', requireUserAuth(), requireOwnerAuth(), handleCleanup(deps));
  app.post('/api/admin/invalidate-cache', requireUserAuth(), requireOwnerAuth(), handleInvalidateCache(deps));
  app.post('/api/admin/personality', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalPersonality(deps));
  app.post('/api/admin/denylist', requireUserAuth(), requireOwnerAuth(), handleAddDenylistEntry(deps));
  app.get('/api/admin/denylist', requireUserAuth(), requireOwnerAuth(), handleListDenylistEntries(deps));
  app.get('/api/admin/llm-config', requireUserAuth(), requireOwnerAuth(), handleListGlobalLlmConfigs(deps));
  app.post('/api/admin/llm-config', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalLlmConfig(deps));
  app.get('/api/admin/tts-config', requireUserAuth(), requireOwnerAuth(), handleListGlobalTtsConfigs(deps));
  app.post('/api/admin/tts-config', requireUserAuth(), requireOwnerAuth(), handleCreateGlobalTtsConfig(deps));
  app.get('/api/admin/settings', requireUserAuth(), requireOwnerAuth(), handleGetAdminSettings(deps));
  app.patch('/api/admin/settings/config-defaults', requireUserAuth(), requireOwnerAuth(), handleUpdateAdminSettings(deps));
  app.delete('/api/admin/settings/config-defaults', requireUserAuth(), requireOwnerAuth(), handleClearAdminSettings(deps));
  app.get('/api/admin/stop-sequences', requireUserAuth(), requireOwnerAuth(), handleGetStopSequencesStats(deps));
  app.get('/api/admin/usage', requireUserAuth(), requireOwnerAuth(), handleGetAdminUsageStats(deps));
  app.patch('/api/admin/personality/:slug', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalPersonality(deps));
  app.get('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleGetGlobalLlmConfig(deps));
  app.put('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalLlmConfig(deps));
  app.put('/api/admin/llm-config/:id/set-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalLlmConfigDefault(deps));
  app.put('/api/admin/llm-config/:id/set-free-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalLlmConfigFreeDefault(deps));
  app.delete('/api/admin/llm-config/:id', requireUserAuth(), requireOwnerAuth(), handleDeleteGlobalLlmConfig(deps));
  app.get('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleGetGlobalTtsConfig(deps));
  app.put('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleUpdateGlobalTtsConfig(deps));
  app.put('/api/admin/tts-config/:id/set-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalTtsConfigDefault(deps));
  app.put('/api/admin/tts-config/:id/set-free-default', requireUserAuth(), requireOwnerAuth(), handleSetGlobalTtsConfigFreeDefault(deps));
  app.delete('/api/admin/tts-config/:id', requireUserAuth(), requireOwnerAuth(), handleDeleteGlobalTtsConfig(deps));
  app.delete('/api/admin/denylist/:type/:discordId/:scope/:scopeId', requireUserAuth(), requireOwnerAuth(), handleRemoveDenylistEntry(deps));
}

export function mountUserRoutes(app: Express, deps: RouteDeps): void {
  app.get('/api/user/timezone', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetTimezone(deps));
  app.put('/api/user/timezone', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTimezone(deps));
  app.get('/api/user/llm-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserLlmConfigs(deps));
  app.post('/api/user/llm-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreateUserLlmConfig(deps));
  app.get('/api/user/tts-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserTtsConfigs(deps));
  app.post('/api/user/tts-config', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreateUserTtsConfig(deps));
  app.get('/api/user/tts-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListTtsOverrides(deps));
  app.put('/api/user/tts-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTtsOverride(deps));
  app.get('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetTtsDefaultConfig(deps));
  app.put('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetTtsDefaultConfig(deps));
  app.delete('/api/user/tts-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearTtsDefaultConfig(deps));
  app.get('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetSttDefaultProvider(deps));
  app.put('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetSttDefaultProvider(deps));
  app.delete('/api/user/stt-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearSttDefaultProvider(deps));
  app.get('/api/user/model-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListModelOverrides(deps));
  app.put('/api/user/model-override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetModelOverride(deps));
  app.get('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetDefaultModelConfig(deps));
  app.put('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetDefaultModelConfig(deps));
  app.delete('/api/user/model-override/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearDefaultModelConfig(deps));
  app.get('/api/user/personality', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonalities(deps));
  app.post('/api/user/personality', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersonality(deps));
  app.get('/api/user/persona', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonas(deps));
  app.post('/api/user/persona', requireUserAuth(), requireProvisionedUser(deps.prisma), handleCreatePersona(deps));
  app.get('/api/user/persona/override', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListPersonaOverrides(deps));
  app.post('/api/user/channel/activate', requireUserAuth(), requireProvisionedUser(deps.prisma), handleActivateChannel(deps));
  app.delete('/api/user/channel/deactivate', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeactivateChannel(deps));
  app.get('/api/user/channel/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListUserChannels(deps));
  app.patch('/api/user/channel/update-guild', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateChannelGuild(deps));
  app.get('/api/user/wallet/list', requireUserAuth(), requireProvisionedUser(deps.prisma), handleListWalletKeys(deps));
  app.post('/api/user/wallet/test', requireUserAuth(), requireProvisionedUser(deps.prisma), handleTestWalletKey(deps));
  app.get('/api/user/voice-resolution', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetVoiceResolution(deps));
  app.get('/api/user/diagnostic/recent', requireUserAuth(), handleGetRecentDiagnostics(deps));
  app.get('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserLlmConfig(deps));
  app.put('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserLlmConfig(deps));
  app.delete('/api/user/llm-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteUserLlmConfig(deps));
  app.get('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserTtsConfig(deps));
  app.put('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdateUserTtsConfig(deps));
  app.delete('/api/user/tts-config/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteUserTtsConfig(deps));
  app.delete('/api/user/tts-override/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteTtsOverride(deps));
  app.delete('/api/user/model-override/:personalityId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeleteModelOverride(deps));
  app.get('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersonality(deps));
  app.put('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleUpdatePersonality(deps));
  app.patch('/api/user/personality/:slug/visibility', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonalityVisibility(deps));
  app.delete('/api/user/personality/:slug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleDeletePersonality(deps));
  app.get('/api/user/persona/:id', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersona(deps));
  app.patch('/api/user/persona/:id/default', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonaDefault(deps));
  app.get('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetPersonaOverride(deps));
  app.put('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleSetPersonaOverride(deps));
  app.delete('/api/user/persona/override/:personalitySlug', requireUserAuth(), requireProvisionedUser(deps.prisma), handleClearPersonaOverride(deps));
  app.get('/api/user/channel/:channelId', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetUserChannel(deps));
  app.get('/api/user/channel/:channelId/config-overrides', requireUserAuth(), requireProvisionedUser(deps.prisma), handleGetChannelConfigOverrides(deps));
  app.delete('/api/user/wallet/:provider', requireUserAuth(), requireProvisionedUser(deps.prisma), handleRemoveWalletKey(deps));
  app.get('/api/user/diagnostic/by-message/:messageId', requireUserAuth(), handleGetDiagnosticByMessage(deps));
  app.get('/api/user/diagnostic/by-response/:messageId', requireUserAuth(), handleGetDiagnosticByResponse(deps));
  app.get('/api/user/diagnostic/:requestId', requireUserAuth(), handleGetDiagnosticByRequestId(deps));
}
