/**
 * Zod Schemas for Tzurot
 *
 * Centralized validation schemas for JSONB fields and API payloads.
 */

export {
  type AdvancedParams,
  AdvancedParamsSchema,
  advancedParamsToConfigFormat,
  type ConvertedLlmParams,
  type ConvertedReasoningConfig,
  hasReasoningEnabled,
  LLM_CONFIG_OVERRIDE_KEYS,
  OpenRouterParamsSchema,
  OutputParamsSchema,
  ReasoningConfigSchema,
  ReasoningParamsSchema,
  safeValidateAdvancedParams,
  SamplingParamsSchema,
  validateReasoningConstraints,
} from './llmAdvancedParams.js';

// API response schemas (contract between gateway and bot-client)
export {
  ActivateChannelRequestSchema,
  ActivateChannelResponseSchema,
  AddDenylistResponseSchema,
  ADMIN_SETTINGS_SINGLETON_ID,
  AdminCleanupResponseSchema,
  AdminPersonalityResponseSchema,
  type AdminSettings,
  AdminSettingsSchema,
  type AdminUsageStats,
  AdminUsageStatsSchema,
  AiConfirmDeliveryResponseSchema,
  AiGenerateResponseSchema,
  AiJobAckResponseSchema,
  AiJobStatusResponseSchema,
  AiTranscribeResponseSchema,
  type BatchDeletePreviewInput,
  BatchDeletePreviewResponseSchema,
  BatchDeletePreviewSchema,
  BatchDeleteResponseSchema,
  BatchDeleteSchema,
  type ChannelSettings,
  ChannelSettingsSchema,
  ClearChannelConfigOverridesResponseSchema,
  type ClearDefaultConfigResponse,
  ClearDefaultConfigResponseSchema,
  ClearHistoryResponseSchema,
  ClearHistorySchema,
  type ClearOverrideResponse,
  ClearOverrideResponseSchema,
  ClearPersonalityConfigOverridesResponseSchema,
  ClearSttDefaultProviderResponseSchema,
  type ClearTtsDefaultConfigResponse,
  ClearTtsDefaultConfigResponseSchema,
  ClearUserConfigDefaultsResponseSchema,
  ClearVoicesResponseSchema,
  type ClonedVoicesSummary,
  ClonedVoicesSummarySchema,
  CONFIG_OVERRIDES_KEYS,
  type ConfigOverrides,
  type ConfigOverrideSource,
  ConfigOverridesSchema,
  ConversationSyncRequestSchema,
  type ConversationSyncResponse,
  ConversationSyncResponseSchema,
  type CreateLlmConfigResponse,
  CreateLlmConfigResponseSchema,
  type CreateOverrideResponse,
  CreateOverrideResponseSchema,
  type CreatePersonalityResponse,
  CreatePersonalityResponseSchema,
  type CreatePersonaResponse,
  CreatePersonaResponseSchema,
  CreateTtsConfigResponseSchema,
  DbSyncResponseSchema,
  DbSyncSchema,
  DeactivateChannelRequestSchema,
  DeactivateChannelResponseSchema,
  type DeleteLlmConfigResponse,
  DeleteLlmConfigResponseSchema,
  DeleteMemoryResponseSchema,
  type DeleteModelOverrideResponse,
  DeleteModelOverrideResponseSchema,
  DeletePersonalityResponseSchema,
  DeletePersonaResponseSchema,
  DeleteShapesAuthResponseSchema,
  DeleteTtsConfigResponseSchema,
  DeleteTtsOverrideResponseSchema,
  DeleteVoiceResponseSchema,
  DenylistAddSchema,
  type DenylistCacheResponse,
  DenylistCacheResponseSchema,
  type DenylistEntityType,
  denylistEntityTypeSchema,
  type DenylistEntry,
  DenylistEntrySchema,
  type DenylistMode,
  denylistModeSchema,
  type DenylistScope,
  denylistScopeSchema,
  type DiagnosticLog,
  type DiagnosticLogResponse,
  DiagnosticLogResponseSchema,
  DiagnosticLogSchema,
  type DiagnosticLogsResponse,
  DiagnosticLogsResponseSchema,
  DiagnosticUpdateResponseSchema,
  DiagnosticUpdateSchema,
  DisableIncognitoResponseSchema,
  DiscordSnowflakeSchema,
  DmSessionSetRequestSchema,
  DmSessionSetResponseSchema,
  emptyToNull,
  EnableIncognitoResponseSchema,
  EntityPermissionsSchema,
  FocusModeSchema,
  FocusModeStatusResponseSchema,
  type GetAdminSettingsResponse,
  GetChannelConfigOverridesResponseSchema,
  type GetChannelSettingsResponse,
  GetChannelSettingsResponseSchema,
  GetIncognitoStatusResponseSchema,
  GetLlmConfigResponseSchema,
  GetNsfwStatusResponseSchema,
  type GetPersonalityResponse,
  GetPersonalityResponseSchema,
  type GetPersonaResponse,
  GetPersonaResponseSchema,
  type GetTimezoneResponse,
  GetTimezoneResponseSchema,
  GetTtsConfigResponseSchema,
  GetTtsDefaultConfigResponseSchema,
  GetUserConfigDefaultsResponseSchema,
  GetVoiceResolutionQuerySchema,
  type GetVoiceResolutionResponse,
  GetVoiceResolutionResponseSchema,
  HARDCODED_CONFIG_DEFAULTS,
  HardDeleteHistoryResponseSchema,
  HardDeleteHistorySchema,
  HistoryStatsQuerySchema,
  HistoryStatsResponseSchema,
  IncognitoForgetResponseSchema,
  type IncognitoSessionWithRemaining,
  IncognitoSessionWithRemainingSchema,
  InvalidateCacheResponseSchema,
  InvalidateCacheSchema,
  IssuePurgeTokenResponseSchema,
  IssuePurgeTokenSchema,
  ListChannelSettingsResponseSchema,
  ListDenylistResponseSchema,
  type ListLlmConfigsResponse,
  ListLlmConfigsResponseSchema,
  type ListModelOverridesResponse,
  ListModelOverridesResponseSchema,
  type ListPersonalitiesResponse,
  ListPersonalitiesResponseSchema,
  ListPersonaOverridesResponseSchema,
  type ListPersonasResponse,
  ListPersonasResponseSchema,
  ListShapesExportJobsResponseSchema,
  ListShapesImportJobsResponseSchema,
  ListShapesResponseSchema,
  ListTtsConfigsResponseSchema,
  ListTtsOverridesResponseSchema,
  ListVoiceModelsResponseSchema,
  ListVoicesResponseSchema,
  type ListWalletKeysResponse,
  ListWalletKeysResponseSchema,
  LLM_CONFIG_DEFAULTS,
  LLM_CONFIG_DETAIL_SELECT,
  LLM_CONFIG_LIST_SELECT,
  type LlmConfigCreateInput,
  LlmConfigCreateSchema,
  type LlmConfigDetail,
  LlmConfigDetailSchema,
  type LlmConfigSummary,
  LlmConfigSummarySchema,
  type LlmConfigUpdateInput,
  LlmConfigUpdateSchema,
  type LoadPersonalityInternalResponse,
  LoadPersonalityInternalResponseSchema,
  type MemoryItem,
  MemoryItemSchema,
  type MemoryListResponse,
  MemoryListResponseSchema,
  MemorySearchResponseSchema,
  MemorySearchResultSchema,
  MemorySearchSchema,
  MemoryStatsResponseSchema,
  MemoryUpdateSchema,
  MessagePersonalityResponseSchema,
  ModelAutocompleteOptionSchema,
  type ModelOverrideSummary,
  ModelOverrideSummarySchema,
  ModelsListResponseSchema,
  nullableString,
  optionalString,
  type OverrideInfoResponse,
  OverrideInfoResponseSchema,
  PersistAssistantMessageRequestSchema,
  type PersistAssistantMessageResponse,
  PersistAssistantMessageResponseSchema,
  PersistUserMessageRequestSchema,
  type PersistUserMessageResponse,
  PersistUserMessageResponseSchema,
  PERSONA_SELECT,
  PersonaCreateSchema,
  type PersonaDetails,
  PersonaDetailsSchema,
  PERSONALITY_DETAIL_SELECT,
  PERSONALITY_LIST_SELECT,
  type PersonalityCharacterFields,
  PersonalityCharacterFieldsSchema,
  type PersonalityCreateInput,
  PersonalityCreateSchema,
  type PersonalityFull,
  PersonalityFullSchema,
  type PersonalitySummary,
  PersonalitySummarySchema,
  type PersonalityUpdateInput,
  PersonalityUpdateSchema,
  type PersonaSummary,
  PersonaSummarySchema,
  type PersonaUpdateInput,
  PersonaUpdateSchema,
  PreviewTokenSchema,
  ProviderWarningSchema,
  PurgeMemoriesResponseSchema,
  PurgeMemoriesSchema,
  PurgeTokenSchema,
  RecentDiagnosticLogSchema,
  type RecentDiagnosticLogsResponse,
  RecentDiagnosticLogsResponseSchema,
  RecentUsersResponseSchema,
  RemoveDenylistResponseSchema,
  type RemoveWalletKeyResponse,
  RemoveWalletKeyResponseSchema,
  type ResolvedConfigOverrides,
  ResolvedConfigOverridesSchema,
  type ResolvedExtendedContextSettings,
  ResolvedExtendedContextSettingsSchema,
  type ResolvedSttView,
  ResolvedSttViewSchema,
  type ResolvedTtsView,
  ResolvedTtsViewSchema,
  ResolveLlmConfigInputSchema,
  ResolveLlmConfigResponseSchema,
  ResolveUserConfigDefaultsResponseSchema,
  type RoutingContextRequest,
  RoutingContextRequestSchema,
  type RoutingContextResponse,
  RoutingContextResponseSchema,
  type SetDefaultConfigResponse,
  SetDefaultConfigResponseSchema,
  SetDefaultConfigSchema,
  type SetDefaultLlmConfigResponse,
  SetDefaultLlmConfigResponseSchema,
  type SetDefaultPersonaResponse,
  SetDefaultPersonaResponseSchema,
  SetDefaultTtsConfigResponseSchema,
  SetFocusResponseSchema,
  SetMemoryLockSchema,
  type SetModelOverrideResponse,
  SetModelOverrideResponseSchema,
  SetModelOverrideSchema,
  type SetOverrideResponse,
  SetOverrideResponseSchema,
  SetPersonaOverrideSchema,
  SetSttDefaultProviderResponseSchema,
  SetSttDefaultProviderSchema,
  SetTimezoneInputSchema,
  type SetTimezoneResponse,
  SetTimezoneResponseSchema,
  type SettingSource,
  SetTtsDefaultConfigResponseSchema,
  SetTtsDefaultConfigSchema,
  SetTtsOverrideResponseSchema,
  SetTtsOverrideSchema,
  SetVisibilitySchema,
  SetWalletKeyResponseSchema,
  SetWalletKeySchema,
  ShapesAuthStatusResponseSchema,
  ShapesExportJobSummarySchema,
  ShapesImportJobSummarySchema,
  ShapesListItemSchema,
  SingleMemoryResponseSchema,
  StartShapesExportInputSchema,
  StartShapesExportResponseSchema,
  StartShapesImportInputSchema,
  StartShapesImportResponseSchema,
  StoreShapesAuthInputSchema,
  StoreShapesAuthResponseSchema,
  type SttResolutionSource,
  SttResolutionSourceSchema,
  TaggedVoiceSchema,
  type TestWalletKeyResponse,
  TestWalletKeyResponseSchema,
  TestWalletKeySchema,
  TopUserUsageSchema,
  TranscribeRequestSchema,
  TTS_CONFIG_DEFAULTS,
  TTS_CONFIG_DETAIL_SELECT,
  TTS_CONFIG_LIST_SELECT,
  TtsAdvancedParamsSchema,
  type TtsConfigCreateInput,
  TtsConfigCreateSchema,
  type TtsConfigSummary,
  TtsConfigSummarySchema,
  type TtsConfigUpdateInput,
  TtsConfigUpdateSchema,
  type TtsOverrideSummary,
  TtsOverrideSummarySchema,
  TtsProviderIdSchema,
  type TtsResolutionSource,
  TtsResolutionSourceSchema,
  UndoHistoryResponseSchema,
  UndoHistorySchema,
  UpdateChannelConfigOverridesRequestSchema,
  UpdateChannelConfigOverridesResponseSchema,
  UpdateChannelGuildRequestSchema,
  UpdateChannelGuildResponseSchema,
  UpdateConfigDefaultsResponseSchema,
  UpdateLlmConfigResponseSchema,
  UpdatePersonalityConfigOverridesResponseSchema,
  UpdatePersonaResponseSchema,
  UpdateTtsConfigResponseSchema,
  UsageBreakdownSchema,
  type UsagePeriod,
  UsagePeriodSchema,
  type UsageStats,
  UsageStatsSchema,
  type UserDefaultConfig,
  UserDefaultConfigSchema,
  type UserDefaultSttProvider,
  UserDefaultSttProviderSchema,
  type UserDefaultTtsConfig,
  UserDefaultTtsConfigSchema,
  VerifyNsfwResponseSchema,
  VoiceModelSchema,
  type WalletKey,
  WalletKeySchema,
} from './api/index.js';
