/**
 * Voice-probe mining for the voice-consistency harness (caching epic, the
 * Phase-1→2 exit gate).
 *
 * Pulls REAL assistant replies + their triggering user turn + the preceding
 * conversation window from `conversation_history`, so the eval can replay the
 * identical inputs through competing prompt-assembly arms and compare the
 * persona's voice. Anchors are restricted to strictly before the beta.190
 * prod deploy, so every probe's `referenceReply` is an authentic
 * pre-restructure production sample (the harness's validity anchor).
 *
 * PRIVACY SCOPE (owner decision): only the OWNER's own conversations are
 * minable. `--owner <discordId>` resolves the owner's persona set; anchor
 * candidates filter to it, and any probe whose window contains a non-owner
 * persona's turn is dropped outright — other users' messages must never reach
 * probes, offline generations, or the LLM judge.
 *
 * Output is LOCAL-ONLY (gitignored `reports/voice-consistency/`) — raw
 * conversation content. What gets committed is THIS miner (deterministic:
 * same DB state → same sample), never the probes.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve, sep } from 'node:path';
import { Prisma, type PrismaClient } from '@tzurot/common-types/services/prisma';
import type { Environment } from '../utils/env-runner.js';
import { pickEvenlySpaced } from '../memory/sampling.js';
import {
  assignDepthStrata,
  detectProtocolFormat,
  pickPersonalities,
  type AnchorCandidate,
  type PersonalityPick,
  type VoiceProbe,
  type VoiceProbeFile,
  type VoiceProbeHistoryEntry,
} from './voice-probes.js';

/** The instant the prompt-restructure release (beta.190) reached prod. Anchors
 * stay strictly before it so no reply generated by the NEW assembly can
 * masquerade as an old-assembly reference sample; override with --cutoff when
 * re-arming the harness for a later phase gate. */
const DEFAULT_CUTOFF_ISO = '2026-08-02T22:00:00Z';
const DEFAULT_DEPTHS = [5, 10, 15, 20, 25, 30];
const DEFAULT_PERSONALITY_COUNT = 4;
const DEFAULT_OUT_DIR = 'reports/voice-consistency';
/** Candidates fetched per depth stratum — window-validation drops (wrong trigger
 * role, short history, non-owner turns) backfill from these. */
const STRATUM_OVER_SAMPLE = 6;

export interface MineVoiceProbesOptions {
  env: Environment;
  /** Discord snowflake of the operator whose conversations are minable. */
  ownerDiscordId: string;
  /** Explicit personality slugs (overrides the activity auto-pick). */
  personalitySlugs?: string[];
  personalityCount?: number;
  depths?: number[];
  /** ISO instant; anchors are strictly before it. */
  cutoff?: string;
  outDir?: string;
}

interface OwnerPersona {
  id: string;
  name: string;
  preferred_name: string | null;
}

interface ActivityRow {
  personality_id: string;
  persona_id: string;
  n: number;
}

interface PersonalityDetailRow {
  id: string;
  slug: string;
  name: string;
  protocol: string | null;
}

interface WindowRow {
  id: string;
  role: string;
  content: string;
  created_at: Date;
  persona_id: string;
  personality_id: string;
  discord_message_id: string[];
  message_metadata: unknown;
  token_count: number | null;
  persona_name: string;
  persona_preferred_name: string | null;
  personality_name: string;
}

interface AnchorRow {
  id: string;
  content: string;
  guild_id: string | null;
  created_at: Date;
}

/** users.discord_id → the owner's persona rows. Hard-errors when unresolvable:
 * a typo'd owner id silently mining nothing would read as "no data". */
async function resolveOwnerPersonaIds(
  prisma: PrismaClient,
  ownerDiscordId: string
): Promise<Set<string>> {
  const users = await prisma.$queryRaw<{ id: string }[]>`
    SELECT id FROM users WHERE discord_id = ${ownerDiscordId}
  `;
  if (users.length === 0) {
    throw new Error(`No user row for discord_id ${ownerDiscordId} — check --owner.`);
  }
  const personas = await prisma.$queryRaw<OwnerPersona[]>`
    SELECT id, name, preferred_name FROM personas WHERE owner_id = ${users[0].id}::uuid
  `;
  if (personas.length === 0) {
    throw new Error(`User ${ownerDiscordId} owns no personas — nothing is minable.`);
  }
  return new Set(personas.map(persona => persona.id));
}

/** Assistant-turn counts per (personality, persona) pre-cutoff, SQL-scoped to
 * the owner's personas so the query rides the [personaId, personalityId,
 * createdAt] index instead of aggregating every user's history (the sibling
 * miners' pattern). The JS re-check stays as a belt for the privacy invariant. */
async function fetchOwnerActivity(
  prisma: PrismaClient,
  cutoff: Date,
  ownerPersonaIds: Set<string>
): Promise<Map<string, number>> {
  // Deliberately no LIMIT: the owner-persona scope + 30-day retention window is
  // the bound (the sibling miners' sanctioned-unbounded pattern), and the GROUP
  // BY output is one row per (personality, persona) — small by construction.
  const rows = await prisma.$queryRaw<ActivityRow[]>`
    SELECT personality_id, persona_id, COUNT(*)::int AS n
    FROM conversation_history
    WHERE role = 'assistant' AND deleted_at IS NULL AND created_at < ${cutoff}
      AND persona_id IN (${Prisma.join([...ownerPersonaIds])})
    GROUP BY personality_id, persona_id
  `;
  const byPersonality = new Map<string, number>();
  for (const row of rows) {
    if (!ownerPersonaIds.has(row.persona_id)) {
      continue;
    }
    byPersonality.set(row.personality_id, (byPersonality.get(row.personality_id) ?? 0) + row.n);
  }
  return byPersonality;
}

async function fetchPersonalityDetail(
  prisma: PrismaClient,
  personalityId: string
): Promise<PersonalityDetailRow | null> {
  const rows = await prisma.$queryRaw<PersonalityDetailRow[]>`
    SELECT p.id, p.slug, p.name, sp.content AS protocol
    FROM personalities p
    LEFT JOIN system_prompts sp ON sp.id = p.system_prompt_id
    WHERE p.id = ${personalityId}::uuid
  `;
  return rows[0] ?? null;
}

/** Build the ranked candidate list (activity + protocol format) for auto-pick. */
async function buildCandidates(
  prisma: PrismaClient,
  activity: Map<string, number>
): Promise<PersonalityPick[]> {
  const candidates: PersonalityPick[] = [];
  for (const [personalityId, assistantTurns] of activity) {
    const detail = await fetchPersonalityDetail(prisma, personalityId);
    if (detail === null) {
      continue;
    }
    candidates.push({
      id: detail.id,
      slug: detail.slug,
      name: detail.name,
      protocolFormat: detectProtocolFormat(detail.protocol),
      assistantTurns,
    });
  }
  return candidates;
}

/** Owner-persona assistant replies pre-cutoff — the anchor candidate pool.
 * SQL-scoped to the owner's personas (index-friendly, sibling-miner pattern);
 * the JS filter below re-checks the privacy invariant. */
async function fetchAnchorCandidates(
  prisma: PrismaClient,
  personalityId: string,
  cutoff: Date,
  ownerPersonaIds: Set<string>
): Promise<AnchorCandidate[]> {
  // Deliberately no LIMIT: stratification needs the full owner×personality
  // time range (a LIMIT would bias toward one era), and the owner-persona +
  // personality + 30-day-retention scope is the bound — the sibling miners'
  // sanctioned-unbounded pattern.
  const rows = await prisma.$queryRaw<
    { id: string; channel_id: string; persona_id: string; created_at: Date }[]
  >`
    SELECT id, channel_id, persona_id, created_at
    FROM conversation_history
    WHERE personality_id = ${personalityId}::uuid
      AND role = 'assistant'
      AND deleted_at IS NULL
      AND created_at < ${cutoff}
      AND persona_id IN (${Prisma.join([...ownerPersonaIds])})
    ORDER BY created_at ASC, id ASC
  `;
  return rows
    .filter(row => ownerPersonaIds.has(row.persona_id))
    .map(row => ({ id: row.id, channelId: row.channel_id, createdAt: new Date(row.created_at) }));
}

/** The depth+1 rows preceding an anchor in its channel (names joined), newest
 * first. NOTE: on a shared channel this pulls non-owner rows into process
 * memory before tryBuildProbe's ownership gate discards the candidate — raw
 * content transits memory but is never written or logged pre-gate. */
async function fetchWindowRows(
  prisma: PrismaClient,
  anchor: AnchorCandidate,
  depth: number
): Promise<WindowRow[]> {
  return prisma.$queryRaw<WindowRow[]>`
    SELECT ch.id, ch.role, ch.content, ch.created_at, ch.persona_id, ch.personality_id,
           ch.discord_message_id, ch.message_metadata, ch.token_count,
           per.name AS persona_name, per.preferred_name AS persona_preferred_name,
           p.name AS personality_name
    FROM conversation_history ch
    JOIN personas per ON per.id = ch.persona_id
    JOIN personalities p ON p.id = ch.personality_id
    WHERE ch.channel_id = ${anchor.channelId}
      AND ch.deleted_at IS NULL
      AND (ch.created_at, ch.id) < (${anchor.createdAt}, ${anchor.id}::uuid)
    ORDER BY ch.created_at DESC, ch.id DESC
    LIMIT ${depth + 1}
  `;
}

function toHistoryEntry(row: WindowRow): VoiceProbeHistoryEntry {
  return {
    id: row.id,
    discordMessageId: row.discord_message_id,
    role: row.role,
    content: row.content,
    createdAt: new Date(row.created_at).toISOString(),
    personaId: row.persona_id,
    personaName: row.persona_preferred_name ?? row.persona_name,
    personalityId: row.personality_id,
    personalityName: row.personality_name,
    tokenCount: row.token_count,
    messageMetadata: row.message_metadata,
  };
}

/**
 * Validate one anchor candidate into a probe: the window must be full (depth+1
 * rows), the immediately-preceding row must be the triggering USER turn, and —
 * the privacy gate — every row's persona must belong to the owner. Assistant
 * rows carry the persona being replied to, so the ownership check covers both
 * roles uniformly.
 */
async function tryBuildProbe(
  prisma: PrismaClient,
  anchor: AnchorCandidate,
  depth: number,
  personality: PersonalityPick,
  ownerPersonaIds: Set<string>
): Promise<VoiceProbe | null> {
  const windowRows = await fetchWindowRows(prisma, anchor, depth);
  if (windowRows.length < depth + 1) {
    return null;
  }
  if (windowRows[0].role !== 'user') {
    return null;
  }
  if (windowRows.some(row => !ownerPersonaIds.has(row.persona_id))) {
    return null;
  }
  const anchorRows = await prisma.$queryRaw<AnchorRow[]>`
    SELECT id, content, guild_id, created_at
    FROM conversation_history
    WHERE id = ${anchor.id}::uuid
  `;
  const anchorRow = anchorRows[0];
  if (anchorRow === undefined) {
    return null;
  }
  const trigger = toHistoryEntry(windowRows[0]);
  const priorHistory = windowRows.slice(1).reverse().map(toHistoryEntry);
  return {
    probeId: anchor.id,
    depth,
    channelId: anchor.channelId,
    guildId: anchorRow.guild_id,
    personality: {
      id: personality.id,
      slug: personality.slug,
      name: personality.name,
      protocolFormat: personality.protocolFormat,
    },
    trigger,
    priorHistory,
    referenceReply: {
      id: anchorRow.id,
      content: anchorRow.content,
      createdAt: new Date(anchorRow.created_at).toISOString(),
    },
  };
}

/** Fill each depth stratum with the first candidate that validates. */
async function collectProbesForPersonality(
  prisma: PrismaClient,
  personality: PersonalityPick,
  anchors: AnchorCandidate[],
  depths: number[],
  ownerPersonaIds: Set<string>
): Promise<{ probes: VoiceProbe[]; unfilled: number[] }> {
  const strata = assignDepthStrata(anchors, depths, STRATUM_OVER_SAMPLE, pickEvenlySpaced);
  const probes: VoiceProbe[] = [];
  const unfilled: number[] = [];
  for (const depth of depths) {
    let filled = false;
    for (const anchor of strata.get(depth) ?? []) {
      const probe = await tryBuildProbe(prisma, anchor, depth, personality, ownerPersonaIds);
      if (probe !== null) {
        probes.push(probe);
        filled = true;
        break;
      }
    }
    if (!filled) {
      unfilled.push(depth);
    }
  }
  return { probes, unfilled };
}

/** Resolve the personality set: explicit slugs (hard-error on unknowns) or the
 * activity auto-pick with format coverage. */
async function resolvePersonalities(
  prisma: PrismaClient,
  options: MineVoiceProbesOptions,
  activity: Map<string, number>
): Promise<{ picked: PersonalityPick[]; warnings: string[] }> {
  const candidates = await buildCandidates(prisma, activity);
  if (options.personalitySlugs !== undefined && options.personalitySlugs.length > 0) {
    const bySlug = new Map(candidates.map(candidate => [candidate.slug, candidate]));
    const picked: PersonalityPick[] = [];
    for (const slug of options.personalitySlugs) {
      const candidate = bySlug.get(slug);
      if (candidate === undefined) {
        throw new Error(
          `--personalities: no owner-conversation activity found for slug "${slug}" before the cutoff.`
        );
      }
      picked.push(candidate);
    }
    // Explicit override deliberately admits protocol-less personalities (the
    // auto-pick excludes them) — explicit means explicit; warn, don't block.
    const warnings = picked
      .filter(candidate => candidate.protocolFormat === 'none')
      .map(candidate => `${candidate.slug} has no protocol — its voice signal is card-only.`);
    return { picked, warnings };
  }
  return pickPersonalities(candidates, options.personalityCount ?? DEFAULT_PERSONALITY_COUNT);
}

/** Mine voice probes. See module header for scope and privacy invariants. */
export async function mineVoiceProbes(options: MineVoiceProbesOptions): Promise<void> {
  const depths = options.depths ?? DEFAULT_DEPTHS;
  const cutoffIso = options.cutoff ?? DEFAULT_CUTOFF_ISO;
  const cutoff = new Date(cutoffIso);
  if (Number.isNaN(cutoff.getTime())) {
    throw new Error(`--cutoff is not a valid ISO instant: ${cutoffIso}`);
  }
  const outDir = options.outDir ?? DEFAULT_OUT_DIR;
  // Privacy invariant, ENFORCED not just stated: probes carry real conversation
  // content and must stay under the gitignored reports/ tree.
  const resolvedOut = resolve(process.cwd(), outDir);
  if (!resolvedOut.startsWith(`${resolve(process.cwd(), 'reports')}${sep}`)) {
    throw new Error(`--out must resolve under reports/ (gitignored), got: ${outDir}`);
  }

  const { getPrismaForEnv } = await import('../memory/prisma-env.js');
  const { prisma, disconnect } = await getPrismaForEnv(options.env);
  try {
    const ownerPersonaIds = await resolveOwnerPersonaIds(prisma, options.ownerDiscordId);
    console.log(`Owner personas in scope: ${ownerPersonaIds.size}`);

    const activity = await fetchOwnerActivity(prisma, cutoff, ownerPersonaIds);
    const { picked, warnings } = await resolvePersonalities(prisma, options, activity);
    if (picked.length === 0) {
      throw new Error('No personalities with owner-conversation activity before the cutoff.');
    }

    const probes: VoiceProbe[] = [];
    for (const personality of picked) {
      const anchors = await fetchAnchorCandidates(prisma, personality.id, cutoff, ownerPersonaIds);
      const collected = await collectProbesForPersonality(
        prisma,
        personality,
        anchors,
        depths,
        ownerPersonaIds
      );
      probes.push(...collected.probes);
      const unfilledNote =
        collected.unfilled.length > 0 ? ` (unfilled depths: ${collected.unfilled.join(', ')})` : '';
      console.log(
        `${personality.slug} [${personality.protocolFormat}] ` +
          `activity=${personality.assistantTurns}: ${collected.probes.length}/${depths.length} probes${unfilledNote}`
      );
    }

    const file: VoiceProbeFile = {
      meta: {
        env: options.env,
        minedAt: new Date().toISOString(),
        cutoff: cutoff.toISOString(),
        depths,
        personalities: picked,
        warnings,
      },
      probes,
    };
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(outDir, 'probes.json'), `${JSON.stringify(file, null, 2)}\n`);

    for (const warning of warnings) {
      console.log(`⚠ ${warning}`);
    }
    console.log(
      `\nWrote ${probes.length} probes to ${outDir}/probes.json (LOCAL-ONLY, gitignored).`
    );
    console.log(
      'VETO MOMENT: review the personality list above before any generation spend — ' +
        're-run with --personalities <slug,slug,...> to override.'
    );
  } finally {
    await disconnect();
  }
}
