/**
 * Snapshot pair + drift gate for the discord.js surface inventory.
 *
 * The committed pair (JSON + markdown) under docs/reference/conformance/ is
 * byte-compared against generator output by `surface:inventory --check`, so
 * every produced string must be deterministic: no timestamps, no elapsed
 * time, no absolute paths.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { compareSurfaceEntries } from './categories.js';
import { SURFACE_CATEGORIES, type SurfaceEntry } from './types.js';

export const SNAPSHOT_DIR = 'docs/reference/conformance';
export const SNAPSHOT_JSON_PATH = `${SNAPSHOT_DIR}/discord-surface.json`;
export const SNAPSHOT_MD_PATH = `${SNAPSHOT_DIR}/discord-surface.md`;

const CHECK_HINT =
  'run `pnpm ops surface:inventory --write`, then commit the refreshed snapshot pair';

const READ_ERROR_HINT =
  'a snapshot file exists but could not be read — fix the file system error first; regenerating the snapshot will not help';

const MIXED_HINT = `one snapshot file exists but could not be read — fix the file system error first; another snapshot file drifted — ${CHECK_HINT}`;

interface SnapshotDocument {
  meta: {
    generator: string;
    scope: string;
    surfaceFamily: string;
    note: string;
  };
  totals: { entries: number; sites: number };
  entries: SurfaceEntry[];
}

function sortEntries(entries: SurfaceEntry[]): SurfaceEntry[] {
  return [...entries].sort(compareSurfaceEntries);
}

function toDocument(entries: SurfaceEntry[]): SnapshotDocument {
  const sorted = sortEntries(entries);
  return {
    meta: {
      generator: 'pnpm ops surface:inventory',
      scope: 'services/bot-client/src (test files excluded)',
      surfaceFamily: 'discord.js, @discordjs/*, discord-api-types declaration paths',
      note: 'doc-109 Appendix A groups 4 (voice) and 7 (snowflakes) are semantic and stay manual',
    },
    totals: {
      entries: sorted.length,
      sites: sorted.reduce((sum, entry) => sum + entry.count, 0),
    },
    entries: sorted,
  };
}

/**
 * Deterministic snapshot bytes for the committed JSON file. elapsedMs is
 * display-only and must never reach these bytes — the drift gate compares
 * them byte-for-byte across machines and runs.
 */
export function buildSnapshotJson(entries: SurfaceEntry[]): string {
  return `${JSON.stringify(toDocument(entries), null, 2)}\n`;
}

/** Deterministic markdown rendering of the snapshot, one section per category. */
export function renderSnapshotMarkdown(entries: SurfaceEntry[]): string {
  const sorted = sortEntries(entries);
  const lines: string[] = [
    '# bot-client discord.js surface snapshot',
    '',
    'Generated by `pnpm ops surface:inventory --write` over a type-checked Program of `services/bot-client/tsconfig.json`.',
    'Scope is `services/bot-client/src` with tests excluded; the surface family is every symbol whose declaration resolves under discord.js / @discordjs/* / discord-api-types declaration paths.',
    'Entries carry file paths and counts only — no line numbers, which churn on every edit.',
    'Refresh with `pnpm ops surface:inventory --write`; gate with `pnpm ops surface:inventory --check`.',
    '',
    'doc-109 Appendix A groups 4 (voice) and 7 (snowflakes) are semantic and stay manual — this snapshot covers the mechanical remainder.',
    'The `unclassified` category is required and never dropped: unmapped constructions and object-literal keys surface there; methods and property accesses land in `client-methods`.',
    'Enum members whose container no table names surface in `discord-enums` under container-qualified names; message-payload option keys with no builder receiver land in `message-options` (the MESSAGE_OPTION_KEYS vocabulary).',
    '`rest-outside-helpers` sees string-literal URLs only.',
    '',
  ];

  for (const category of SURFACE_CATEGORIES) {
    const inCategory = sorted.filter(entry => entry.category === category);
    lines.push(`## ${category}`);
    lines.push('');
    if (inCategory.length === 0) {
      lines.push('(no entries)');
      lines.push('');
      continue;
    }
    lines.push('| file | symbol | count |');
    lines.push('| --- | --- | --- |');
    for (const entry of inCategory) {
      lines.push(`| ${entry.file} | ${entry.symbol} | ${entry.count} |`);
    }
    lines.push('');
  }

  const sites = sorted.reduce((sum, entry) => sum + entry.count, 0);
  lines.push(`Total: ${sorted.length} entries across ${sites} sites.`);
  return `${lines.join('\n')}\n`;
}

export interface SurfaceCheckResult {
  ok: boolean;
  /** Offending repo-relative snapshot paths, each with its drift reason. */
  drifted: string[];
  hint: string;
}

/**
 * Extract the Node fs error code from a caught read failure, when the thrown
 * value carries one (ENOENT, EISDIR, …). The catch clause types the error
 * `unknown`, so the shape is narrowed without any runtime dependency.
 */
function readErrorCode(error: unknown): string | undefined {
  if (typeof error !== 'object' || error === null || !('code' in error)) return undefined;
  const code = error.code;
  return typeof code === 'string' ? code : undefined;
}

/**
 * Byte-compare the committed snapshot pair against freshly generated bytes.
 * A missing file is drift, not an error — the gate's first run on a fresh
 * clone without the pair must point at `--write`. Any other read error names
 * the error code and switches the hint: regenerating cannot help when the
 * file exists but cannot be read. When BOTH kinds occur in one run (the pair
 * is two files: one unreadable, one drifted), the hint carries both
 * instructions, since fixing only the unreadable file would still leave the
 * gate red on the next run.
 */
export function evaluateCheck(rootDir: string, entries: SurfaceEntry[]): SurfaceCheckResult {
  const expected: [path: string, content: string][] = [
    [SNAPSHOT_JSON_PATH, buildSnapshotJson(entries)],
    [SNAPSHOT_MD_PATH, renderSnapshotMarkdown(entries)],
  ];
  const drifted: string[] = [];
  let anyUnreadable = false;
  let anyDrift = false;
  for (const [relativePath, content] of expected) {
    let actual: string | undefined;
    let errorCode: string | undefined;
    try {
      actual = readFileSync(join(rootDir, relativePath), 'utf-8');
    } catch (error) {
      actual = undefined;
      errorCode = readErrorCode(error);
    }
    if (actual !== undefined) {
      if (actual !== content) {
        drifted.push(relativePath);
        anyDrift = true;
      }
    } else if (errorCode === undefined || errorCode === 'ENOENT') {
      drifted.push(`${relativePath} (missing)`);
      anyDrift = true;
    } else {
      drifted.push(`${relativePath} (${errorCode})`);
      anyUnreadable = true;
    }
  }
  return {
    ok: drifted.length === 0,
    drifted,
    hint: anyUnreadable ? (anyDrift ? MIXED_HINT : READ_ERROR_HINT) : CHECK_HINT,
  };
}

/** Write both snapshot files, creating the directory when missing. */
export function writeSnapshotFiles(rootDir: string, json: string, md: string): void {
  const dir = join(rootDir, SNAPSHOT_DIR);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(rootDir, SNAPSHOT_JSON_PATH), json);
  writeFileSync(join(rootDir, SNAPSHOT_MD_PATH), md);
}
