/**
 * Shared header emitted at the top of every generated route artifact.
 *
 * The marker line is what bypasses the husky pre-commit temporal-marker
 * check (.husky/pre-commit) — files whose first 200 chars contain
 * "AUTO-GENERATED FILE" are skipped during PR-number / date scanning.
 *
 * Also signals to humans that hand-edits will be wiped on the next
 * `pnpm ops codegen:routes` run.
 */

export const AUTOGEN_HEADER = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/clients/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */
`;
