/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/clients/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

import { z } from 'zod';
import { callGateway, type GatewayResult } from '../transport.js';
import { ROUTE_MANIFEST } from '../../routes/manifest.js';
import { type ActorDiscordId } from '../../routes/types.js';

function buildQueryString(entries: Array<[string, string | undefined]>): string {
  const defined = entries.filter((e): e is [string, string] => e[1] !== undefined);
  if (defined.length === 0) return '';
  const qs = new URLSearchParams();
  for (const [k, v] of defined) qs.set(k, v);
  return '?' + qs.toString();
}

export interface OwnerClientOptions {
  /** Full gateway base URL, e.g. https://api-gateway.example.com. */
  baseUrl: string;
  /** Shared service secret (sent as X-Service-Auth). */
  serviceSecret: string;
  /** Discord ID of the actor making the call (the bot owner / the user). */
  actor: ActorDiscordId;
}

export class OwnerClient {
  private readonly baseUrl: string;
  private readonly serviceSecret: string;
  readonly actor: ActorDiscordId;

  constructor(options: OwnerClientOptions) {
    this.baseUrl = options.baseUrl;
    this.serviceSecret = options.serviceSecret;
    this.actor = options.actor;
  }

  async dbSync(input: z.input<typeof ROUTE_MANIFEST.dbSync.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.dbSync.output>>> {
    const fullPath = '/api/admin/db-sync';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.dbSync.output,
      timeoutMs: ROUTE_MANIFEST.dbSync.timeoutMs,
    });
  }

  async broadcast(input: z.input<typeof ROUTE_MANIFEST.broadcast.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.broadcast.output>>> {
    const fullPath = '/api/admin/broadcast';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.broadcast.output,
    });
  }

  async cleanup(input: z.input<typeof ROUTE_MANIFEST.cleanup.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.cleanup.output>>> {
    const fullPath = '/api/admin/cleanup';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.cleanup.output,
      timeoutMs: ROUTE_MANIFEST.cleanup.timeoutMs,
    });
  }

  async invalidateCache(input: z.input<typeof ROUTE_MANIFEST.invalidateCache.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.invalidateCache.output>>> {
    const fullPath = '/api/admin/invalidate-cache';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.invalidateCache.output,
    });
  }

  async createGlobalPersonality(input: z.input<typeof ROUTE_MANIFEST.createGlobalPersonality.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createGlobalPersonality.output>>> {
    const fullPath = '/api/admin/personality';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createGlobalPersonality.output,
    });
  }

  async updateGlobalPersonality(slug: string, input: z.input<typeof ROUTE_MANIFEST.updateGlobalPersonality.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateGlobalPersonality.output>>> {
    const fullPath = `/api/admin/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateGlobalPersonality.output,
    });
  }

  async addDenylistEntry(input: z.input<typeof ROUTE_MANIFEST.addDenylistEntry.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.addDenylistEntry.output>>> {
    const fullPath = '/api/admin/denylist';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.addDenylistEntry.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listDenylistEntries(options: { type?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listDenylistEntries.output>>> {
    const fullPath = '/api/admin/denylist' + buildQueryString([['type', options.type]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.listDenylistEntries.output,
    });
  }

  async removeDenylistEntry(type: string, discordId: string, scope: string, scopeId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.removeDenylistEntry.output>>> {
    const fullPath = `/api/admin/denylist/${encodeURIComponent(type)}/${encodeURIComponent(discordId)}/${encodeURIComponent(scope)}/${encodeURIComponent(scopeId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.removeDenylistEntry.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listGlobalLlmConfigs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listGlobalLlmConfigs.output>>> {
    const fullPath = '/api/admin/llm-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.listGlobalLlmConfigs.output,
      timeoutMs: ROUTE_MANIFEST.listGlobalLlmConfigs.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getGlobalLlmConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getGlobalLlmConfig.output>>> {
    const fullPath = `/api/admin/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.getGlobalLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.getGlobalLlmConfig.timeoutMs,
    });
  }

  async createGlobalLlmConfig(input: z.input<typeof ROUTE_MANIFEST.createGlobalLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createGlobalLlmConfig.output>>> {
    const fullPath = '/api/admin/llm-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createGlobalLlmConfig.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updateGlobalLlmConfig(id: string, input: z.input<typeof ROUTE_MANIFEST.updateGlobalLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateGlobalLlmConfig.output>>> {
    const fullPath = `/api/admin/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateGlobalLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.updateGlobalLlmConfig.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setGlobalLlmConfigDefault(id: string, options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setGlobalLlmConfigDefault.output>>> {
    const fullPath = `/api/admin/llm-config/${encodeURIComponent(id)}/set-default` + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.setGlobalLlmConfigDefault.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setGlobalLlmConfigFreeDefault(id: string, options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setGlobalLlmConfigFreeDefault.output>>> {
    const fullPath = `/api/admin/llm-config/${encodeURIComponent(id)}/set-free-default` + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.setGlobalLlmConfigFreeDefault.output,
    });
  }

  async deleteGlobalLlmConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteGlobalLlmConfig.output>>> {
    const fullPath = `/api/admin/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.deleteGlobalLlmConfig.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listGlobalTtsConfigs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listGlobalTtsConfigs.output>>> {
    const fullPath = '/api/admin/tts-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.listGlobalTtsConfigs.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getGlobalTtsConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getGlobalTtsConfig.output>>> {
    const fullPath = `/api/admin/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.getGlobalTtsConfig.output,
    });
  }

  async createGlobalTtsConfig(input: z.input<typeof ROUTE_MANIFEST.createGlobalTtsConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createGlobalTtsConfig.output>>> {
    const fullPath = '/api/admin/tts-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createGlobalTtsConfig.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updateGlobalTtsConfig(id: string, input: z.input<typeof ROUTE_MANIFEST.updateGlobalTtsConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateGlobalTtsConfig.output>>> {
    const fullPath = `/api/admin/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateGlobalTtsConfig.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setGlobalTtsConfigDefault(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setGlobalTtsConfigDefault.output>>> {
    const fullPath = `/api/admin/tts-config/${encodeURIComponent(id)}/set-default`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.setGlobalTtsConfigDefault.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setGlobalTtsConfigFreeDefault(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setGlobalTtsConfigFreeDefault.output>>> {
    const fullPath = `/api/admin/tts-config/${encodeURIComponent(id)}/set-free-default`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.setGlobalTtsConfigFreeDefault.output,
    });
  }

  async deleteGlobalTtsConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteGlobalTtsConfig.output>>> {
    const fullPath = `/api/admin/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.deleteGlobalTtsConfig.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getAdminSettings(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getAdminSettings.output>>> {
    const fullPath = '/api/admin/settings';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.getAdminSettings.output,
    });
  }

  async updateAdminSettings(input: z.input<typeof ROUTE_MANIFEST.updateAdminSettings.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateAdminSettings.output>>> {
    const fullPath = '/api/admin/settings/config-defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateAdminSettings.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getSystemSettings(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getSystemSettings.output>>> {
    const fullPath = '/api/admin/settings/system';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.getSystemSettings.output,
    });
  }

  async updateSystemSettings(input: z.input<typeof ROUTE_MANIFEST.updateSystemSettings.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateSystemSettings.output>>> {
    const fullPath = '/api/admin/settings/system';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateSystemSettings.output,
    });
  }

  async clearAdminSettings(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearAdminSettings.output>>> {
    const fullPath = '/api/admin/settings/config-defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.clearAdminSettings.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getAdminUsageStats(options: { timeframe?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getAdminUsageStats.output>>> {
    const fullPath = '/api/admin/usage' + buildQueryString([['timeframe', options.timeframe]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
      },
      outputSchema: ROUTE_MANIFEST.getAdminUsageStats.output,
    });
  }
}
