/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Regenerated by: pnpm ops codegen:routes
 *
 * Source of truth: packages/clients/src/routes/manifest.ts
 *
 * To change a generated artifact, edit the manifest entry in
 * routes/{internal,admin,user}.ts and re-run the codegen tool.
 * The pre-commit hook will regenerate + auto-stage on manifest changes.
 *
 * Lint is disabled for this directory at the eslint config level
 * (see eslint.config.js global ignores); no in-file disables needed.
 */

import { z } from 'zod';
import { callGateway, type GatewayResult } from '../transport.js';
import { ROUTE_MANIFEST } from '../../routes/manifest.js';
import { type ActorDiscordId, type SubjectDiscordId } from '../../routes/types.js';
import type { GatewayUser } from '@tzurot/common-types/types/gateway-context';

function buildQueryString(entries: Array<[string, string | undefined]>): string {
  const defined = entries.filter((e): e is [string, string] => e[1] !== undefined);
  if (defined.length === 0) return '';
  const qs = new URLSearchParams();
  for (const [k, v] of defined) qs.set(k, v);
  return '?' + qs.toString();
}

export interface UserClientOptions {
  /** Full gateway base URL, e.g. https://api-gateway.example.com. */
  baseUrl: string;
  /** Shared service secret (sent as X-Service-Auth). */
  serviceSecret: string;
  /** Discord ID of the actor making the call (the bot owner / the user). */
  actor: ActorDiscordId;
  /** Full Discord user context for user-context headers. */
  user: GatewayUser;
}

export class UserClient {
  private readonly baseUrl: string;
  private readonly serviceSecret: string;
  readonly actor: ActorDiscordId;
  readonly user: GatewayUser;

  constructor(options: UserClientOptions) {
    this.baseUrl = options.baseUrl;
    this.serviceSecret = options.serviceSecret;
    this.actor = options.actor;
    this.user = options.user;
  }

  async startAccountExport(input: z.input<typeof ROUTE_MANIFEST.startAccountExport.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.startAccountExport.output>>> {
    const fullPath = '/api/user/account/export';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.startAccountExport.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getAccountExportStatus(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getAccountExportStatus.output>>> {
    const fullPath = '/api/user/account/export/status';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getAccountExportStatus.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async previewAccountDelete(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.previewAccountDelete.output>>> {
    const fullPath = '/api/user/account/delete/preview';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.previewAccountDelete.output,
    });
  }

  async issueAccountDeleteToken(input: z.input<typeof ROUTE_MANIFEST.issueAccountDeleteToken.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.issueAccountDeleteToken.output>>> {
    const fullPath = '/api/user/account/delete/token';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.issueAccountDeleteToken.output,
    });
  }

  /**
   * @atMostOnce Mutating + single-use-token guarded; replay yields a 4xx token-expired error even though the original mutation succeeded server-side. Retry layers must NOT auto-retry — surface the original error to the user only if no success response was observed.
   */
  async deleteAccount(input: z.input<typeof ROUTE_MANIFEST.deleteAccount.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteAccount.output>>> {
    const fullPath = '/api/user/account/delete';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.deleteAccount.output,
      timeoutMs: ROUTE_MANIFEST.deleteAccount.timeoutMs,
    });
  }

  async submitFeedback(input: z.input<typeof ROUTE_MANIFEST.submitFeedback.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.submitFeedback.output>>> {
    const fullPath = '/api/user/feedback';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.submitFeedback.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getTimezone(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getTimezone.output>>> {
    const fullPath = '/api/user/timezone';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getTimezone.output,
      timeoutMs: ROUTE_MANIFEST.getTimezone.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setTimezone(input: z.input<typeof ROUTE_MANIFEST.setTimezone.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setTimezone.output>>> {
    const fullPath = '/api/user/timezone';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setTimezone.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getNotificationPrefs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getNotificationPrefs.output>>> {
    const fullPath = '/api/user/notifications';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getNotificationPrefs.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updateNotificationPrefs(input: z.input<typeof ROUTE_MANIFEST.updateNotificationPrefs.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateNotificationPrefs.output>>> {
    const fullPath = '/api/user/notifications';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateNotificationPrefs.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listReleaseDms(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listReleaseDms.output>>> {
    const fullPath = '/api/user/notifications/release-dms';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listReleaseDms.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async markReleaseDmsDeleted(input: z.input<typeof ROUTE_MANIFEST.markReleaseDmsDeleted.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.markReleaseDmsDeleted.output>>> {
    const fullPath = '/api/user/notifications/release-dms/deleted';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.markReleaseDmsDeleted.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listUserLlmConfigs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listUserLlmConfigs.output>>> {
    const fullPath = '/api/user/llm-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listUserLlmConfigs.output,
      timeoutMs: ROUTE_MANIFEST.listUserLlmConfigs.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getUserLlmConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserLlmConfig.output>>> {
    const fullPath = `/api/user/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getUserLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.getUserLlmConfig.timeoutMs,
    });
  }

  async createUserLlmConfig(input: z.input<typeof ROUTE_MANIFEST.createUserLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createUserLlmConfig.output>>> {
    const fullPath = '/api/user/llm-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createUserLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.createUserLlmConfig.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updateUserLlmConfig(id: string, input: z.input<typeof ROUTE_MANIFEST.updateUserLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateUserLlmConfig.output>>> {
    const fullPath = `/api/user/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateUserLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.updateUserLlmConfig.timeoutMs,
    });
  }

  async deleteUserLlmConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteUserLlmConfig.output>>> {
    const fullPath = `/api/user/llm-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteUserLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.deleteUserLlmConfig.timeoutMs,
    });
  }

  async resolveUserLlmConfig(input: z.input<typeof ROUTE_MANIFEST.resolveUserLlmConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolveUserLlmConfig.output>>> {
    const fullPath = '/api/user/llm-config/resolve';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.resolveUserLlmConfig.output,
      timeoutMs: ROUTE_MANIFEST.resolveUserLlmConfig.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listUserTtsConfigs(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listUserTtsConfigs.output>>> {
    const fullPath = '/api/user/tts-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listUserTtsConfigs.output,
      timeoutMs: ROUTE_MANIFEST.listUserTtsConfigs.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getUserTtsConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserTtsConfig.output>>> {
    const fullPath = `/api/user/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getUserTtsConfig.output,
    });
  }

  async createUserTtsConfig(input: z.input<typeof ROUTE_MANIFEST.createUserTtsConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createUserTtsConfig.output>>> {
    const fullPath = '/api/user/tts-config';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createUserTtsConfig.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updateUserTtsConfig(id: string, input: z.input<typeof ROUTE_MANIFEST.updateUserTtsConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateUserTtsConfig.output>>> {
    const fullPath = `/api/user/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateUserTtsConfig.output,
    });
  }

  async deleteUserTtsConfig(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteUserTtsConfig.output>>> {
    const fullPath = `/api/user/tts-config/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteUserTtsConfig.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listTtsOverrides(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listTtsOverrides.output>>> {
    const fullPath = '/api/user/tts-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listTtsOverrides.output,
      timeoutMs: ROUTE_MANIFEST.listTtsOverrides.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setTtsOverride(input: z.input<typeof ROUTE_MANIFEST.setTtsOverride.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setTtsOverride.output>>> {
    const fullPath = '/api/user/tts-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setTtsOverride.output,
    });
  }

  async deleteTtsOverride(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteTtsOverride.output>>> {
    const fullPath = `/api/user/tts-override/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteTtsOverride.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getTtsDefaultConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getTtsDefaultConfig.output>>> {
    const fullPath = '/api/user/tts-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getTtsDefaultConfig.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setTtsDefaultConfig(input: z.input<typeof ROUTE_MANIFEST.setTtsDefaultConfig.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setTtsDefaultConfig.output>>> {
    const fullPath = '/api/user/tts-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setTtsDefaultConfig.output,
    });
  }

  async clearTtsDefaultConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearTtsDefaultConfig.output>>> {
    const fullPath = '/api/user/tts-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearTtsDefaultConfig.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getSttDefaultProvider(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getSttDefaultProvider.output>>> {
    const fullPath = '/api/user/stt-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getSttDefaultProvider.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setSttDefaultProvider(input: z.input<typeof ROUTE_MANIFEST.setSttDefaultProvider.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setSttDefaultProvider.output>>> {
    const fullPath = '/api/user/stt-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setSttDefaultProvider.output,
    });
  }

  async clearSttDefaultProvider(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearSttDefaultProvider.output>>> {
    const fullPath = '/api/user/stt-override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearSttDefaultProvider.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listModelOverrides(options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listModelOverrides.output>>> {
    const fullPath = '/api/user/model-override' + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listModelOverrides.output,
      timeoutMs: ROUTE_MANIFEST.listModelOverrides.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setModelOverride(input: z.input<typeof ROUTE_MANIFEST.setModelOverride.input>, options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setModelOverride.output>>> {
    const fullPath = '/api/user/model-override' + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setModelOverride.output,
    });
  }

  async deleteModelOverride(personalityId: string, options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteModelOverride.output>>> {
    const fullPath = `/api/user/model-override/${encodeURIComponent(personalityId)}` + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteModelOverride.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getDefaultModelConfig(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDefaultModelConfig.output>>> {
    const fullPath = '/api/user/model-override/default';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getDefaultModelConfig.output,
      timeoutMs: ROUTE_MANIFEST.getDefaultModelConfig.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setDefaultModelConfig(input: z.input<typeof ROUTE_MANIFEST.setDefaultModelConfig.input>, options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setDefaultModelConfig.output>>> {
    const fullPath = '/api/user/model-override/default' + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setDefaultModelConfig.output,
    });
  }

  async clearDefaultModelConfig(options: { slot?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearDefaultModelConfig.output>>> {
    const fullPath = '/api/user/model-override/default' + buildQueryString([['slot', options.slot]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearDefaultModelConfig.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listPersonalities(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonalities.output>>> {
    const fullPath = '/api/user/personality';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listPersonalities.output,
      timeoutMs: ROUTE_MANIFEST.listPersonalities.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getPersonality(slug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getPersonality.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getPersonality.output,
      timeoutMs: ROUTE_MANIFEST.getPersonality.timeoutMs,
    });
  }

  async createPersonality(input: z.input<typeof ROUTE_MANIFEST.createPersonality.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createPersonality.output>>> {
    const fullPath = '/api/user/personality';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createPersonality.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updatePersonality(slug: string, input: z.input<typeof ROUTE_MANIFEST.updatePersonality.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersonality.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersonality.output,
    });
  }

  async setPersonalityVisibility(slug: string, input: z.input<typeof ROUTE_MANIFEST.setPersonalityVisibility.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setPersonalityVisibility.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}/visibility`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setPersonalityVisibility.output,
    });
  }

  async deletePersonality(slug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deletePersonality.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deletePersonality.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listPersonalityAliases(slug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonalityAliases.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}/aliases`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listPersonalityAliases.output,
    });
  }

  async addPersonalityAlias(slug: string, input: z.input<typeof ROUTE_MANIFEST.addPersonalityAlias.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.addPersonalityAlias.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}/aliases`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.addPersonalityAlias.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async removePersonalityAlias(slug: string, alias: string, options: { scope?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.removePersonalityAlias.output>>> {
    const fullPath = `/api/user/personality/${encodeURIComponent(slug)}/aliases/${encodeURIComponent(alias)}` + buildQueryString([['scope', options.scope]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.removePersonalityAlias.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listMyAliases(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listMyAliases.output>>> {
    const fullPath = '/api/user/personality/my-aliases';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listMyAliases.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listPersonas(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonas.output>>> {
    const fullPath = '/api/user/persona';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listPersonas.output,
      timeoutMs: ROUTE_MANIFEST.listPersonas.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getPersona(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getPersona.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getPersona.output,
      timeoutMs: ROUTE_MANIFEST.getPersona.timeoutMs,
    });
  }

  async createPersona(input: z.input<typeof ROUTE_MANIFEST.createPersona.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createPersona.output>>> {
    const fullPath = '/api/user/persona';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createPersona.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updatePersona(id: string, input: z.input<typeof ROUTE_MANIFEST.updatePersona.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersona.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersona.output,
    });
  }

  async deletePersona(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deletePersona.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deletePersona.output,
    });
  }

  async setPersonaDefault(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setPersonaDefault.output>>> {
    const fullPath = `/api/user/persona/${encodeURIComponent(id)}/default`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.setPersonaDefault.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listPersonaOverrides(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listPersonaOverrides.output>>> {
    const fullPath = '/api/user/persona/override';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listPersonaOverrides.output,
      timeoutMs: ROUTE_MANIFEST.listPersonaOverrides.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getPersonaOverride(personalitySlug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/${encodeURIComponent(personalitySlug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getPersonaOverride.output,
      timeoutMs: ROUTE_MANIFEST.getPersonaOverride.timeoutMs,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setPersonaOverride(personalitySlug: string, input: z.input<typeof ROUTE_MANIFEST.setPersonaOverride.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/${encodeURIComponent(personalitySlug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setPersonaOverride.output,
    });
  }

  async clearPersonaOverride(personalitySlug: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/${encodeURIComponent(personalitySlug)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearPersonaOverride.output,
    });
  }

  async createPersonaOverride(personalityId: string, input: z.input<typeof ROUTE_MANIFEST.createPersonaOverride.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.createPersonaOverride.output>>> {
    const fullPath = `/api/user/persona/override/by-id/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.createPersonaOverride.output,
    });
  }

  async activateChannel(input: z.input<typeof ROUTE_MANIFEST.activateChannel.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.activateChannel.output>>> {
    const fullPath = '/api/user/channel/activate';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.activateChannel.output,
    });
  }

  async deactivateChannel(input: z.input<typeof ROUTE_MANIFEST.deactivateChannel.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deactivateChannel.output>>> {
    const fullPath = '/api/user/channel/deactivate';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.deactivateChannel.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listUserChannels(options: { guildId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listUserChannels.output>>> {
    const fullPath = '/api/user/channel/list' + buildQueryString([['guildId', options.guildId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listUserChannels.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getUserChannel(channelId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserChannel.output>>> {
    const fullPath = `/api/user/channel/${encodeURIComponent(channelId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getUserChannel.output,
    });
  }

  async updateChannelGuild(input: z.input<typeof ROUTE_MANIFEST.updateChannelGuild.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateChannelGuild.output>>> {
    const fullPath = '/api/user/channel/update-guild';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateChannelGuild.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getChannelConfigOverrides(channelId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getChannelConfigOverrides.output>>> {
    const fullPath = `/api/user/channel/${encodeURIComponent(channelId)}/config-overrides`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getChannelConfigOverrides.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async updateChannelConfigOverrides(channelId: string, input: z.input<typeof ROUTE_MANIFEST.updateChannelConfigOverrides.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateChannelConfigOverrides.output>>> {
    const fullPath = `/api/user/channel/${encodeURIComponent(channelId)}/config-overrides`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateChannelConfigOverrides.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async clearChannelConfigOverrides(channelId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearChannelConfigOverrides.output>>> {
    const fullPath = `/api/user/channel/${encodeURIComponent(channelId)}/config-overrides`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearChannelConfigOverrides.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getUserUsage(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserUsage.output>>> {
    const fullPath = '/api/user/usage';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getUserUsage.output,
    });
  }

  async clearHistory(input: z.input<typeof ROUTE_MANIFEST.clearHistory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearHistory.output>>> {
    const fullPath = '/api/user/history/clear';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.clearHistory.output,
    });
  }

  async undoHistory(input: z.input<typeof ROUTE_MANIFEST.undoHistory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.undoHistory.output>>> {
    const fullPath = '/api/user/history/undo';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.undoHistory.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getHistoryStats(options: { personalitySlug: string; channelId: string; personaId?: string }): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getHistoryStats.output>>> {
    const fullPath = '/api/user/history/stats' + buildQueryString([['personalitySlug', options.personalitySlug], ['channelId', options.channelId], ['personaId', options.personaId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getHistoryStats.output,
    });
  }

  async hardDeleteHistory(input: z.input<typeof ROUTE_MANIFEST.hardDeleteHistory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.hardDeleteHistory.output>>> {
    const fullPath = '/api/user/history/hard-delete';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.hardDeleteHistory.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getNsfwStatus(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getNsfwStatus.output>>> {
    const fullPath = '/api/user/nsfw';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getNsfwStatus.output,
    });
  }

  async verifyNsfw(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.verifyNsfw.output>>> {
    const fullPath = '/api/user/nsfw/verify';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.verifyNsfw.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listWalletKeys(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listWalletKeys.output>>> {
    const fullPath = '/api/user/wallet/list';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listWalletKeys.output,
      timeoutMs: ROUTE_MANIFEST.listWalletKeys.timeoutMs,
    });
  }

  async setWalletKey(input: z.input<typeof ROUTE_MANIFEST.setWalletKey.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setWalletKey.output>>> {
    const fullPath = '/api/user/wallet/set';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setWalletKey.output,
      timeoutMs: ROUTE_MANIFEST.setWalletKey.timeoutMs,
    });
  }

  async removeWalletKey(provider: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.removeWalletKey.output>>> {
    const fullPath = `/api/user/wallet/${encodeURIComponent(provider)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.removeWalletKey.output,
    });
  }

  async testWalletKey(input: z.input<typeof ROUTE_MANIFEST.testWalletKey.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.testWalletKey.output>>> {
    const fullPath = '/api/user/wallet/test';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.testWalletKey.output,
      timeoutMs: ROUTE_MANIFEST.testWalletKey.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getVoiceResolution(options: { personalityId: string }): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getVoiceResolution.output>>> {
    const fullPath = '/api/user/voice-resolution' + buildQueryString([['personalityId', options.personalityId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getVoiceResolution.output,
      timeoutMs: ROUTE_MANIFEST.getVoiceResolution.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listVoices(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listVoices.output>>> {
    const fullPath = '/api/user/voices';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listVoices.output,
      timeoutMs: ROUTE_MANIFEST.listVoices.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listVoiceModels(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listVoiceModels.output>>> {
    const fullPath = '/api/user/voices/models';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listVoiceModels.output,
      timeoutMs: ROUTE_MANIFEST.listVoiceModels.timeoutMs,
    });
  }

  async clearVoices(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearVoices.output>>> {
    const fullPath = '/api/user/voices/clear';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearVoices.output,
      timeoutMs: ROUTE_MANIFEST.clearVoices.timeoutMs,
    });
  }

  async deleteVoice(provider: string, voiceId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteVoice.output>>> {
    const fullPath = `/api/user/voices/${encodeURIComponent(provider)}/${encodeURIComponent(voiceId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteVoice.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getStats(options: { personalityId: string }): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getStats.output>>> {
    const fullPath = '/api/user/memory/stats' + buildQueryString([['personalityId', options.personalityId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getStats.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   * @softDeleteAware Resource has a soft-delete column; soft-deleted rows may be returned or filtered depending on handler semantics.
   */
  async list(options: { personalityId?: string; limit?: string; offset?: string; sort?: string; order?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.list.output>>> {
    const fullPath = '/api/user/memory/list' + buildQueryString([['personalityId', options.personalityId], ['limit', options.limit], ['offset', options.offset], ['sort', options.sort], ['order', options.order]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.list.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getFocus(options: { personalityId: string }): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getFocus.output>>> {
    const fullPath = '/api/user/memory/focus' + buildQueryString([['personalityId', options.personalityId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getFocus.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setFocus(input: z.input<typeof ROUTE_MANIFEST.setFocus.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setFocus.output>>> {
    const fullPath = '/api/user/memory/focus';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setFocus.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async search(input: z.input<typeof ROUTE_MANIFEST.search.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.search.output>>> {
    const fullPath = '/api/user/memory/search';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.search.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async batchDeletePreview(input: z.input<typeof ROUTE_MANIFEST.batchDeletePreview.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.batchDeletePreview.output>>> {
    const fullPath = '/api/user/memory/delete/preview';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.batchDeletePreview.output,
    });
  }

  /**
   * @atMostOnce Mutating + single-use-token guarded; replay yields a 4xx token-expired error even though the original mutation succeeded server-side. Retry layers must NOT auto-retry — surface the original error to the user only if no success response was observed.
   */
  async batchDelete(input: z.input<typeof ROUTE_MANIFEST.batchDelete.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.batchDelete.output>>> {
    const fullPath = '/api/user/memory/delete';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.batchDelete.output,
    });
  }

  async issuePurgeToken(input: z.input<typeof ROUTE_MANIFEST.issuePurgeToken.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.issuePurgeToken.output>>> {
    const fullPath = '/api/user/memory/purge/token';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.issuePurgeToken.output,
    });
  }

  /**
   * @atMostOnce Mutating + single-use-token guarded; replay yields a 4xx token-expired error even though the original mutation succeeded server-side. Retry layers must NOT auto-retry — surface the original error to the user only if no success response was observed.
   */
  async purge(input: z.input<typeof ROUTE_MANIFEST.purge.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.purge.output>>> {
    const fullPath = '/api/user/memory/purge';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.purge.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   * @softDeleteAware Resource has a soft-delete column; soft-deleted rows may be returned or filtered depending on handler semantics.
   */
  async getMemory(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getMemory.output>>> {
    const fullPath = `/api/user/memory/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getMemory.output,
    });
  }

  async updateMemory(id: string, input: z.input<typeof ROUTE_MANIFEST.updateMemory.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateMemory.output>>> {
    const fullPath = `/api/user/memory/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateMemory.output,
    });
  }

  async deleteMemory(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteMemory.output>>> {
    const fullPath = `/api/user/memory/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteMemory.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setMemoryLock(id: string, input: z.input<typeof ROUTE_MANIFEST.setMemoryLock.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setMemoryLock.output>>> {
    const fullPath = `/api/user/memory/${encodeURIComponent(id)}/lock`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setMemoryLock.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getIncognitoStatus(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getIncognitoStatus.output>>> {
    const fullPath = '/api/user/memory/incognito';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getIncognitoStatus.output,
    });
  }

  async enableIncognito(input: z.input<typeof ROUTE_MANIFEST.enableIncognito.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.enableIncognito.output>>> {
    const fullPath = '/api/user/memory/incognito';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.enableIncognito.output,
    });
  }

  async disableIncognito(input: z.input<typeof ROUTE_MANIFEST.disableIncognito.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.disableIncognito.output>>> {
    const fullPath = '/api/user/memory/incognito';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.disableIncognito.output,
    });
  }

  async incognitoForget(input: z.input<typeof ROUTE_MANIFEST.incognitoForget.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.incognitoForget.output>>> {
    const fullPath = '/api/user/memory/incognito/forget';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.incognitoForget.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   * @softDeleteAware Resource has a soft-delete column; soft-deleted rows may be returned or filtered depending on handler semantics.
   */
  async listFacts(options: { personalityId: string; limit?: string; offset?: string }): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listFacts.output>>> {
    const fullPath = '/api/user/fact/list' + buildQueryString([['personalityId', options.personalityId], ['limit', options.limit], ['offset', options.offset]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listFacts.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   * @softDeleteAware Resource has a soft-delete column; soft-deleted rows may be returned or filtered depending on handler semantics.
   */
  async getFact(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getFact.output>>> {
    const fullPath = `/api/user/fact/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getFact.output,
    });
  }

  async correctFact(id: string, input: z.input<typeof ROUTE_MANIFEST.correctFact.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.correctFact.output>>> {
    const fullPath = `/api/user/fact/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.correctFact.output,
    });
  }

  async forgetFact(id: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.forgetFact.output>>> {
    const fullPath = `/api/user/fact/${encodeURIComponent(id)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.forgetFact.output,
    });
  }

  /**
   * @idempotent Replaying the exact same request lands the same final state — safe to retry on network failure.
   */
  async setFactLock(id: string, input: z.input<typeof ROUTE_MANIFEST.setFactLock.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.setFactLock.output>>> {
    const fullPath = `/api/user/fact/${encodeURIComponent(id)}/lock`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PUT',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.setFactLock.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async resolveUserDefaults(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolveUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/resolve-defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.resolveUserDefaults.output,
      timeoutMs: ROUTE_MANIFEST.resolveUserDefaults.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getUserDefaults(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getUserDefaults.output,
      timeoutMs: ROUTE_MANIFEST.getUserDefaults.timeoutMs,
    });
  }

  async updateUserDefaults(input: z.input<typeof ROUTE_MANIFEST.updateUserDefaults.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updateUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updateUserDefaults.output,
    });
  }

  async clearUserDefaults(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearUserDefaults.output>>> {
    const fullPath = '/api/user/config-overrides/defaults';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearUserDefaults.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async resolveCascade(personalityId: string, options: { channelId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolveCascade.output>>> {
    const fullPath = `/api/user/config-overrides/resolve/${encodeURIComponent(personalityId)}` + buildQueryString([['channelId', options.channelId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.resolveCascade.output,
      timeoutMs: ROUTE_MANIFEST.resolveCascade.timeoutMs,
    });
  }

  async updatePersonalityOverrides(personalityId: string, input: z.input<typeof ROUTE_MANIFEST.updatePersonalityOverrides.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersonalityOverrides.output>>> {
    const fullPath = `/api/user/config-overrides/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersonalityOverrides.output,
    });
  }

  async clearPersonalityOverrides(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.clearPersonalityOverrides.output>>> {
    const fullPath = `/api/user/config-overrides/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.clearPersonalityOverrides.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async resolvePersonalityCascade(personalityId: string): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.resolvePersonalityCascade.output>>> {
    const fullPath = `/api/user/config-overrides/resolve-personality/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.resolvePersonalityCascade.output,
      timeoutMs: ROUTE_MANIFEST.resolvePersonalityCascade.timeoutMs,
    });
  }

  async updatePersonalityConfigDefaults(personalityId: string, input: z.input<typeof ROUTE_MANIFEST.updatePersonalityConfigDefaults.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.updatePersonalityConfigDefaults.output>>> {
    const fullPath = `/api/user/config-overrides/personality/${encodeURIComponent(personalityId)}`;
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'PATCH',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.updatePersonalityConfigDefaults.output,
    });
  }

  async storeShapesAuth(input: z.input<typeof ROUTE_MANIFEST.storeShapesAuth.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.storeShapesAuth.output>>> {
    const fullPath = '/api/user/shapes/auth';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.storeShapesAuth.output,
      timeoutMs: ROUTE_MANIFEST.storeShapesAuth.timeoutMs,
    });
  }

  async deleteShapesAuth(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.deleteShapesAuth.output>>> {
    const fullPath = '/api/user/shapes/auth';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'DELETE',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.deleteShapesAuth.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getShapesAuthStatus(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getShapesAuthStatus.output>>> {
    const fullPath = '/api/user/shapes/auth/status';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getShapesAuthStatus.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listShapes(): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listShapes.output>>> {
    const fullPath = '/api/user/shapes/list';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listShapes.output,
      timeoutMs: ROUTE_MANIFEST.listShapes.timeoutMs,
    });
  }

  async startShapesImport(input: z.input<typeof ROUTE_MANIFEST.startShapesImport.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.startShapesImport.output>>> {
    const fullPath = '/api/user/shapes/import';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.startShapesImport.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listShapesImportJobs(options: { slug?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listShapesImportJobs.output>>> {
    const fullPath = '/api/user/shapes/import/jobs' + buildQueryString([['slug', options.slug]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listShapesImportJobs.output,
    });
  }

  async startShapesExport(input: z.input<typeof ROUTE_MANIFEST.startShapesExport.input>): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.startShapesExport.output>>> {
    const fullPath = '/api/user/shapes/export';
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'POST',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      body: input,
      outputSchema: ROUTE_MANIFEST.startShapesExport.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async listShapesExportJobs(options: { slug?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.listShapesExportJobs.output>>> {
    const fullPath = '/api/user/shapes/export/jobs' + buildQueryString([['slug', options.slug]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.listShapesExportJobs.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getRecentDiagnostics(options: { subject?: SubjectDiscordId; personalityId?: string } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getRecentDiagnostics.output>>> {
    const fullPath = '/api/user/diagnostic/recent' + buildQueryString([['userId', options.subject], ['personalityId', options.personalityId]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getRecentDiagnostics.output,
      timeoutMs: ROUTE_MANIFEST.getRecentDiagnostics.timeoutMs,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getDiagnosticByMessage(messageId: string, options: { subject?: SubjectDiscordId } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDiagnosticByMessage.output>>> {
    const fullPath = `/api/user/diagnostic/by-message/${encodeURIComponent(messageId)}` + buildQueryString([['userId', options.subject]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getDiagnosticByMessage.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getDiagnosticByResponse(messageId: string, options: { subject?: SubjectDiscordId } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDiagnosticByResponse.output>>> {
    const fullPath = `/api/user/diagnostic/by-response/${encodeURIComponent(messageId)}` + buildQueryString([['userId', options.subject]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getDiagnosticByResponse.output,
    });
  }

  /**
   * @safeRead Server-side has no observable mutation — safe to cache client-side.
   */
  async getDiagnosticByRequestId(requestId: string, options: { subject?: SubjectDiscordId } = {}): Promise<GatewayResult<z.infer<typeof ROUTE_MANIFEST.getDiagnosticByRequestId.output>>> {
    const fullPath = `/api/user/diagnostic/${encodeURIComponent(requestId)}` + buildQueryString([['userId', options.subject]]);
    return callGateway({
      baseUrl: this.baseUrl,
      serviceSecret: this.serviceSecret,
      method: 'GET',
      path: fullPath,
      headers: {
        'X-User-Id': this.actor,
        'X-User-Username': encodeURIComponent(this.user.username),
        'X-User-DisplayName': encodeURIComponent(this.user.displayName),
        'X-User-Is-Bot': String(this.user.isBot),
      },
      outputSchema: ROUTE_MANIFEST.getDiagnosticByRequestId.output,
    });
  }
}
